// NewlyNow.com — full catalog: platforms as cards, grouped by section dividers
window.faIcon = function (ic) { ic = ic || 'fa-layer-group'; if (ic.indexOf(' ') > -1) return ic; return 'fas ' + ic; };
window.catDesc = function (t) { return 'كل ' + (t || 'الخدمات') + ' — جودة عالية وتنفيذ آمن.'; };
window.CATEGORIES = {
  "ai__chatgpt": { icon: "fas fa-robot", g1: "#7C3AED", g2: "#4F46E5", order: 0, section: "ai", sectionTitle: "🤖 اشتراكات وحسابات الذكاء الاصطناعي",
    title: "ChatGPT", intro: "كل خدمات ChatGPT في مكان واحد — جودة عالية وتنفيذ آمن.",
    groups: [ { h: "خدمات ChatGPT", items: ["اشتراك شهري","اشتراك 3 شهور","اشتراك سنوي","حساب جاهز"] } ] },
  "ai__claude": { icon: "fas fa-robot", g1: "#7C3AED", g2: "#4F46E5", order: 1, section: "ai", sectionTitle: "🤖 اشتراكات وحسابات الذكاء الاصطناعي",
    title: "Claude", intro: "كل خدمات Claude في مكان واحد — جودة عالية وتنفيذ آمن.",
    groups: [ { h: "خدمات Claude", items: ["اشتراك شهري","اشتراك 3 شهور","اشتراك سنوي","حساب جاهز"] } ] },
  "ai__gemini": { icon: "fas fa-robot", g1: "#7C3AED", g2: "#4F46E5", order: 2, section: "ai", sectionTitle: "🤖 اشتراكات وحسابات الذكاء الاصطناعي",
    title: "Gemini", intro: "كل خدمات Gemini في مكان واحد — جودة عالية وتنفيذ آمن.",
    groups: [ { h: "خدمات Gemini", items: ["اشتراك شهري","اشتراك 3 شهور","اشتراك سنوي","حساب جاهز"] } ] },
  "ai__grok": { icon: "fas fa-robot", g1: "#7C3AED", g2: "#4F46E5", order: 3, section: "ai", sectionTitle: "🤖 اشتراكات وحسابات الذكاء الاصطناعي",
    title: "Grok", intro: "كل خدمات Grok في مكان واحد — جودة عالية وتنفيذ آمن.",
    groups: [ { h: "خدمات Grok", items: ["اشتراك شهري","اشتراك 3 شهور","اشتراك سنوي","حساب جاهز"] } ] },
  "ai__midjourney": { icon: "fas fa-robot", g1: "#7C3AED", g2: "#4F46E5", order: 4, section: "ai", sectionTitle: "🤖 اشتراكات وحسابات الذكاء الاصطناعي",
    title: "Midjourney", intro: "كل خدمات Midjourney في مكان واحد — جودة عالية وتنفيذ آمن.",
    groups: [ { h: "خدمات Midjourney", items: ["اشتراك شهري","اشتراك 3 شهور","اشتراك سنوي","حساب جاهز"] } ] },
  "ai__dall-e": { icon: "fas fa-robot", g1: "#7C3AED", g2: "#4F46E5", order: 5, section: "ai", sectionTitle: "🤖 اشتراكات وحسابات الذكاء الاصطناعي",
    title: "DALL·E", intro: "كل خدمات DALL·E في مكان واحد — جودة عالية وتنفيذ آمن.",
    groups: [ { h: "خدمات DALL·E", items: ["اشتراك شهري","اشتراك 3 شهور","اشتراك سنوي","حساب جاهز"] } ] },
  "ai__leonardo-ai": { icon: "fas fa-robot", g1: "#7C3AED", g2: "#4F46E5", order: 6, section: "ai", sectionTitle: "🤖 اشتراكات وحسابات الذكاء الاصطناعي",
    title: "Leonardo AI", intro: "كل خدمات Leonardo AI في مكان واحد — جودة عالية وتنفيذ آمن.",
    groups: [ { h: "خدمات Leonardo AI", items: ["اشتراك شهري","اشتراك 3 شهور","اشتراك سنوي","حساب جاهز"] } ] },
  "ai__runway": { icon: "fas fa-robot", g1: "#7C3AED", g2: "#4F46E5", order: 7, section: "ai", sectionTitle: "🤖 اشتراكات وحسابات الذكاء الاصطناعي",
    title: "Runway", intro: "كل خدمات Runway في مكان واحد — جودة عالية وتنفيذ آمن.",
    groups: [ { h: "خدمات Runway", items: ["اشتراك شهري","اشتراك 3 شهور","اشتراك سنوي","حساب جاهز"] } ] },
  "ai__kling-ai": { icon: "fas fa-robot", g1: "#7C3AED", g2: "#4F46E5", order: 8, section: "ai", sectionTitle: "🤖 اشتراكات وحسابات الذكاء الاصطناعي",
    title: "Kling AI", intro: "كل خدمات Kling AI في مكان واحد — جودة عالية وتنفيذ آمن.",
    groups: [ { h: "خدمات Kling AI", items: ["اشتراك شهري","اشتراك 3 شهور","اشتراك سنوي","حساب جاهز"] } ] },
  "ai__veo": { icon: "fas fa-robot", g1: "#7C3AED", g2: "#4F46E5", order: 9, section: "ai", sectionTitle: "🤖 اشتراكات وحسابات الذكاء الاصطناعي",
    title: "Veo", intro: "كل خدمات Veo في مكان واحد — جودة عالية وتنفيذ آمن.",
    groups: [ { h: "خدمات Veo", items: ["اشتراك شهري","اشتراك 3 شهور","اشتراك سنوي","حساب جاهز"] } ] },
  "ai__elevenlabs": { icon: "fas fa-robot", g1: "#7C3AED", g2: "#4F46E5", order: 10, section: "ai", sectionTitle: "🤖 اشتراكات وحسابات الذكاء الاصطناعي",
    title: "ElevenLabs", intro: "كل خدمات ElevenLabs في مكان واحد — جودة عالية وتنفيذ آمن.",
    groups: [ { h: "خدمات ElevenLabs", items: ["اشتراك شهري","اشتراك 3 شهور","اشتراك سنوي","حساب جاهز"] } ] },
  "ai__suno": { icon: "fas fa-robot", g1: "#7C3AED", g2: "#4F46E5", order: 11, section: "ai", sectionTitle: "🤖 اشتراكات وحسابات الذكاء الاصطناعي",
    title: "Suno", intro: "كل خدمات Suno في مكان واحد — جودة عالية وتنفيذ آمن.",
    groups: [ { h: "خدمات Suno", items: ["اشتراك شهري","اشتراك 3 شهور","اشتراك سنوي","حساب جاهز"] } ] },
  "ai__udio": { icon: "fas fa-robot", g1: "#7C3AED", g2: "#4F46E5", order: 12, section: "ai", sectionTitle: "🤖 اشتراكات وحسابات الذكاء الاصطناعي",
    title: "Udio", intro: "كل خدمات Udio في مكان واحد — جودة عالية وتنفيذ آمن.",
    groups: [ { h: "خدمات Udio", items: ["اشتراك شهري","اشتراك 3 شهور","اشتراك سنوي","حساب جاهز"] } ] },
  "ai__cursor-ai": { icon: "fas fa-robot", g1: "#7C3AED", g2: "#4F46E5", order: 13, section: "ai", sectionTitle: "🤖 اشتراكات وحسابات الذكاء الاصطناعي",
    title: "Cursor AI", intro: "كل خدمات Cursor AI في مكان واحد — جودة عالية وتنفيذ آمن.",
    groups: [ { h: "خدمات Cursor AI", items: ["اشتراك شهري","اشتراك 3 شهور","اشتراك سنوي","حساب جاهز"] } ] },
  "ai__manus-ai": { icon: "fas fa-robot", g1: "#7C3AED", g2: "#4F46E5", order: 14, section: "ai", sectionTitle: "🤖 اشتراكات وحسابات الذكاء الاصطناعي",
    title: "Manus AI", intro: "كل خدمات Manus AI في مكان واحد — جودة عالية وتنفيذ آمن.",
    groups: [ { h: "خدمات Manus AI", items: ["اشتراك شهري","اشتراك 3 شهور","اشتراك سنوي","حساب جاهز"] } ] },
  "ai__perplexity": { icon: "fas fa-robot", g1: "#7C3AED", g2: "#4F46E5", order: 15, section: "ai", sectionTitle: "🤖 اشتراكات وحسابات الذكاء الاصطناعي",
    title: "Perplexity", intro: "كل خدمات Perplexity في مكان واحد — جودة عالية وتنفيذ آمن.",
    groups: [ { h: "خدمات Perplexity", items: ["اشتراك شهري","اشتراك 3 شهور","اشتراك سنوي","حساب جاهز"] } ] },
  "ai__notion-ai": { icon: "fas fa-robot", g1: "#7C3AED", g2: "#4F46E5", order: 16, section: "ai", sectionTitle: "🤖 اشتراكات وحسابات الذكاء الاصطناعي",
    title: "Notion AI", intro: "كل خدمات Notion AI في مكان واحد — جودة عالية وتنفيذ آمن.",
    groups: [ { h: "خدمات Notion AI", items: ["اشتراك شهري","اشتراك 3 شهور","اشتراك سنوي","حساب جاهز"] } ] },
  "ai__canva-ai": { icon: "fas fa-robot", g1: "#7C3AED", g2: "#4F46E5", order: 17, section: "ai", sectionTitle: "🤖 اشتراكات وحسابات الذكاء الاصطناعي",
    title: "Canva AI", intro: "كل خدمات Canva AI في مكان واحد — جودة عالية وتنفيذ آمن.",
    groups: [ { h: "خدمات Canva AI", items: ["اشتراك شهري","اشتراك 3 شهور","اشتراك سنوي","حساب جاهز"] } ] },
  "ai__github-copilot": { icon: "fas fa-robot", g1: "#7C3AED", g2: "#4F46E5", order: 18, section: "ai", sectionTitle: "🤖 اشتراكات وحسابات الذكاء الاصطناعي",
    title: "GitHub Copilot", intro: "كل خدمات GitHub Copilot في مكان واحد — جودة عالية وتنفيذ آمن.",
    groups: [ { h: "خدمات GitHub Copilot", items: ["اشتراك شهري","اشتراك 3 شهور","اشتراك سنوي","حساب جاهز"] } ] },
  "ai__replit-ai": { icon: "fas fa-robot", g1: "#7C3AED", g2: "#4F46E5", order: 19, section: "ai", sectionTitle: "🤖 اشتراكات وحسابات الذكاء الاصطناعي",
    title: "Replit AI", intro: "كل خدمات Replit AI في مكان واحد — جودة عالية وتنفيذ آمن.",
    groups: [ { h: "خدمات Replit AI", items: ["اشتراك شهري","اشتراك 3 شهور","اشتراك سنوي","حساب جاهز"] } ] },
  "ai__lovable": { icon: "fas fa-robot", g1: "#7C3AED", g2: "#4F46E5", order: 20, section: "ai", sectionTitle: "🤖 اشتراكات وحسابات الذكاء الاصطناعي",
    title: "Lovable", intro: "كل خدمات Lovable في مكان واحد — جودة عالية وتنفيذ آمن.",
    groups: [ { h: "خدمات Lovable", items: ["اشتراك شهري","اشتراك 3 شهور","اشتراك سنوي","حساب جاهز"] } ] },
  "ai__bolt-new": { icon: "fas fa-robot", g1: "#7C3AED", g2: "#4F46E5", order: 21, section: "ai", sectionTitle: "🤖 اشتراكات وحسابات الذكاء الاصطناعي",
    title: "Bolt.new", intro: "كل خدمات Bolt.new في مكان واحد — جودة عالية وتنفيذ آمن.",
    groups: [ { h: "خدمات Bolt.new", items: ["اشتراك شهري","اشتراك 3 شهور","اشتراك سنوي","حساب جاهز"] } ] },
  "ai__n8n": { icon: "fas fa-robot", g1: "#7C3AED", g2: "#4F46E5", order: 22, section: "ai", sectionTitle: "🤖 اشتراكات وحسابات الذكاء الاصطناعي",
    title: "n8n", intro: "كل خدمات n8n في مكان واحد — جودة عالية وتنفيذ آمن.",
    groups: [ { h: "خدمات n8n", items: ["اشتراك شهري","اشتراك 3 شهور","اشتراك سنوي","حساب جاهز"] } ] },
  "ai__zapier": { icon: "fas fa-robot", g1: "#7C3AED", g2: "#4F46E5", order: 23, section: "ai", sectionTitle: "🤖 اشتراكات وحسابات الذكاء الاصطناعي",
    title: "Zapier", intro: "كل خدمات Zapier في مكان واحد — جودة عالية وتنفيذ آمن.",
    groups: [ { h: "خدمات Zapier", items: ["اشتراك شهري","اشتراك 3 شهور","اشتراك سنوي","حساب جاهز"] } ] },
  "ai__make-integromat": { icon: "fas fa-robot", g1: "#7C3AED", g2: "#4F46E5", order: 24, section: "ai", sectionTitle: "🤖 اشتراكات وحسابات الذكاء الاصطناعي",
    title: "Make (Integromat)", intro: "كل خدمات Make (Integromat) في مكان واحد — جودة عالية وتنفيذ آمن.",
    groups: [ { h: "خدمات Make (Integromat)", items: ["اشتراك شهري","اشتراك 3 شهور","اشتراك سنوي","حساب جاهز"] } ] },
  "social__facebook": { icon: "fab fa-facebook", g1: "#2F6FED", g2: "#17C8AC", order: 25, section: "social", sectionTitle: "📱 منصات التواصل الاجتماعي",
    title: "Facebook", intro: "كل خدمات Facebook في مكان واحد — جودة عالية وتنفيذ آمن.",
    groups: [ { h: "خدمات Facebook", items: ["زيادة متابعين","لايكات","مشاهدات","تعليقات","مشاركات"] } ] },
  "social__instagram": { icon: "fab fa-instagram", g1: "#2F6FED", g2: "#17C8AC", order: 26, section: "social", sectionTitle: "📱 منصات التواصل الاجتماعي",
    title: "Instagram", intro: "كل خدمات Instagram في مكان واحد — جودة عالية وتنفيذ آمن.",
    groups: [ { h: "خدمات Instagram", items: ["زيادة متابعين","لايكات","مشاهدات","تعليقات","مشاركات"] } ] },
  "social__tiktok": { icon: "fab fa-tiktok", g1: "#2F6FED", g2: "#17C8AC", order: 27, section: "social", sectionTitle: "📱 منصات التواصل الاجتماعي",
    title: "TikTok", intro: "كل خدمات TikTok في مكان واحد — جودة عالية وتنفيذ آمن.",
    groups: [ { h: "خدمات TikTok", items: ["زيادة متابعين","لايكات","مشاهدات","تعليقات","مشاركات"] } ] },
  "social__youtube": { icon: "fab fa-youtube", g1: "#2F6FED", g2: "#17C8AC", order: 28, section: "social", sectionTitle: "📱 منصات التواصل الاجتماعي",
    title: "YouTube", intro: "كل خدمات YouTube في مكان واحد — جودة عالية وتنفيذ آمن.",
    groups: [ { h: "خدمات YouTube", items: ["زيادة متابعين","لايكات","مشاهدات","تعليقات","مشاركات"] } ] },
  "social__snapchat": { icon: "fab fa-snapchat", g1: "#2F6FED", g2: "#17C8AC", order: 29, section: "social", sectionTitle: "📱 منصات التواصل الاجتماعي",
    title: "Snapchat", intro: "كل خدمات Snapchat في مكان واحد — جودة عالية وتنفيذ آمن.",
    groups: [ { h: "خدمات Snapchat", items: ["زيادة متابعين","لايكات","مشاهدات","تعليقات","مشاركات"] } ] },
  "social__x-twitter": { icon: "fas fa-share-nodes", g1: "#2F6FED", g2: "#17C8AC", order: 30, section: "social", sectionTitle: "📱 منصات التواصل الاجتماعي",
    title: "X (Twitter)", intro: "كل خدمات X (Twitter) في مكان واحد — جودة عالية وتنفيذ آمن.",
    groups: [ { h: "خدمات X (Twitter)", items: ["زيادة متابعين","لايكات","مشاهدات","تعليقات","مشاركات"] } ] },
  "social__telegram": { icon: "fab fa-telegram", g1: "#2F6FED", g2: "#17C8AC", order: 31, section: "social", sectionTitle: "📱 منصات التواصل الاجتماعي",
    title: "Telegram", intro: "كل خدمات Telegram في مكان واحد — جودة عالية وتنفيذ آمن.",
    groups: [ { h: "خدمات Telegram", items: ["زيادة متابعين","لايكات","مشاهدات","تعليقات","مشاركات"] } ] },
  "social__whatsapp": { icon: "fab fa-whatsapp", g1: "#2F6FED", g2: "#17C8AC", order: 32, section: "social", sectionTitle: "📱 منصات التواصل الاجتماعي",
    title: "WhatsApp", intro: "كل خدمات WhatsApp في مكان واحد — جودة عالية وتنفيذ آمن.",
    groups: [ { h: "خدمات WhatsApp", items: ["زيادة متابعين","لايكات","مشاهدات","تعليقات","مشاركات"] } ] },
  "social__threads": { icon: "fab fa-threads", g1: "#2F6FED", g2: "#17C8AC", order: 33, section: "social", sectionTitle: "📱 منصات التواصل الاجتماعي",
    title: "Threads", intro: "كل خدمات Threads في مكان واحد — جودة عالية وتنفيذ آمن.",
    groups: [ { h: "خدمات Threads", items: ["زيادة متابعين","لايكات","مشاهدات","تعليقات","مشاركات"] } ] },
  "social__linkedin": { icon: "fab fa-linkedin", g1: "#2F6FED", g2: "#17C8AC", order: 34, section: "social", sectionTitle: "📱 منصات التواصل الاجتماعي",
    title: "LinkedIn", intro: "كل خدمات LinkedIn في مكان واحد — جودة عالية وتنفيذ آمن.",
    groups: [ { h: "خدمات LinkedIn", items: ["زيادة متابعين","لايكات","مشاهدات","تعليقات","مشاركات"] } ] },
  "social__pinterest": { icon: "fab fa-pinterest", g1: "#2F6FED", g2: "#17C8AC", order: 35, section: "social", sectionTitle: "📱 منصات التواصل الاجتماعي",
    title: "Pinterest", intro: "كل خدمات Pinterest في مكان واحد — جودة عالية وتنفيذ آمن.",
    groups: [ { h: "خدمات Pinterest", items: ["زيادة متابعين","لايكات","مشاهدات","تعليقات","مشاركات"] } ] },
  "social__reddit": { icon: "fab fa-reddit", g1: "#2F6FED", g2: "#17C8AC", order: 36, section: "social", sectionTitle: "📱 منصات التواصل الاجتماعي",
    title: "Reddit", intro: "كل خدمات Reddit في مكان واحد — جودة عالية وتنفيذ آمن.",
    groups: [ { h: "خدمات Reddit", items: ["زيادة متابعين","لايكات","مشاهدات","تعليقات","مشاركات"] } ] },
  "social__discord": { icon: "fab fa-discord", g1: "#2F6FED", g2: "#17C8AC", order: 37, section: "social", sectionTitle: "📱 منصات التواصل الاجتماعي",
    title: "Discord", intro: "كل خدمات Discord في مكان واحد — جودة عالية وتنفيذ آمن.",
    groups: [ { h: "خدمات Discord", items: ["زيادة متابعين","لايكات","مشاهدات","تعليقات","مشاركات"] } ] },
  "social__twitch": { icon: "fab fa-twitch", g1: "#2F6FED", g2: "#17C8AC", order: 38, section: "social", sectionTitle: "📱 منصات التواصل الاجتماعي",
    title: "Twitch", intro: "كل خدمات Twitch في مكان واحد — جودة عالية وتنفيذ آمن.",
    groups: [ { h: "خدمات Twitch", items: ["زيادة متابعين","لايكات","مشاهدات","تعليقات","مشاركات"] } ] },
  "social__kick": { icon: "fas fa-share-nodes", g1: "#2F6FED", g2: "#17C8AC", order: 39, section: "social", sectionTitle: "📱 منصات التواصل الاجتماعي",
    title: "Kick", intro: "كل خدمات Kick في مكان واحد — جودة عالية وتنفيذ آمن.",
    groups: [ { h: "خدمات Kick", items: ["زيادة متابعين","لايكات","مشاهدات","تعليقات","مشاركات"] } ] },
  "social__facebook-messenger": { icon: "fas fa-share-nodes", g1: "#2F6FED", g2: "#17C8AC", order: 40, section: "social", sectionTitle: "📱 منصات التواصل الاجتماعي",
    title: "Facebook Messenger", intro: "كل خدمات Facebook Messenger في مكان واحد — جودة عالية وتنفيذ آمن.",
    groups: [ { h: "خدمات Facebook Messenger", items: ["زيادة متابعين","لايكات","مشاهدات","تعليقات","مشاركات"] } ] },
  "social__wechat": { icon: "fab fa-weixin", g1: "#2F6FED", g2: "#17C8AC", order: 41, section: "social", sectionTitle: "📱 منصات التواصل الاجتماعي",
    title: "WeChat", intro: "كل خدمات WeChat في مكان واحد — جودة عالية وتنفيذ آمن.",
    groups: [ { h: "خدمات WeChat", items: ["زيادة متابعين","لايكات","مشاهدات","تعليقات","مشاركات"] } ] },
  "social__line": { icon: "fas fa-share-nodes", g1: "#2F6FED", g2: "#17C8AC", order: 42, section: "social", sectionTitle: "📱 منصات التواصل الاجتماعي",
    title: "LINE", intro: "كل خدمات LINE في مكان واحد — جودة عالية وتنفيذ آمن.",
    groups: [ { h: "خدمات LINE", items: ["زيادة متابعين","لايكات","مشاهدات","تعليقات","مشاركات"] } ] },
  "social__vk": { icon: "fas fa-share-nodes", g1: "#2F6FED", g2: "#17C8AC", order: 43, section: "social", sectionTitle: "📱 منصات التواصل الاجتماعي",
    title: "VK", intro: "كل خدمات VK في مكان واحد — جودة عالية وتنفيذ آمن.",
    groups: [ { h: "خدمات VK", items: ["زيادة متابعين","لايكات","مشاهدات","تعليقات","مشاركات"] } ] },
  "social__tumblr": { icon: "fas fa-share-nodes", g1: "#2F6FED", g2: "#17C8AC", order: 44, section: "social", sectionTitle: "📱 منصات التواصل الاجتماعي",
    title: "Tumblr", intro: "كل خدمات Tumblr في مكان واحد — جودة عالية وتنفيذ آمن.",
    groups: [ { h: "خدمات Tumblr", items: ["زيادة متابعين","لايكات","مشاهدات","تعليقات","مشاركات"] } ] },
  "social__quora": { icon: "fas fa-share-nodes", g1: "#2F6FED", g2: "#17C8AC", order: 45, section: "social", sectionTitle: "📱 منصات التواصل الاجتماعي",
    title: "Quora", intro: "كل خدمات Quora في مكان واحد — جودة عالية وتنفيذ آمن.",
    groups: [ { h: "خدمات Quora", items: ["زيادة متابعين","لايكات","مشاهدات","تعليقات","مشاركات"] } ] },
  "games__pubg-mobile": { icon: "fas fa-gamepad", g1: "#F43F5E", g2: "#FB923C", order: 46, section: "games", sectionTitle: "🎮 شحن الألعاب",
    title: "PUBG Mobile", intro: "كل خدمات PUBG Mobile في مكان واحد — جودة عالية وتنفيذ آمن.",
    groups: [ { h: "خدمات PUBG Mobile", items: ["شحن","بطاقة شحن","حساب"] } ] },
  "games__free-fire": { icon: "fas fa-gamepad", g1: "#F43F5E", g2: "#FB923C", order: 47, section: "games", sectionTitle: "🎮 شحن الألعاب",
    title: "Free Fire", intro: "كل خدمات Free Fire في مكان واحد — جودة عالية وتنفيذ آمن.",
    groups: [ { h: "خدمات Free Fire", items: ["شحن","بطاقة شحن","حساب"] } ] },
  "games__fortnite": { icon: "fas fa-gamepad", g1: "#F43F5E", g2: "#FB923C", order: 48, section: "games", sectionTitle: "🎮 شحن الألعاب",
    title: "Fortnite", intro: "كل خدمات Fortnite في مكان واحد — جودة عالية وتنفيذ آمن.",
    groups: [ { h: "خدمات Fortnite", items: ["شحن","بطاقة شحن","حساب"] } ] },
  "games__valorant": { icon: "fas fa-gamepad", g1: "#F43F5E", g2: "#FB923C", order: 49, section: "games", sectionTitle: "🎮 شحن الألعاب",
    title: "Valorant", intro: "كل خدمات Valorant في مكان واحد — جودة عالية وتنفيذ آمن.",
    groups: [ { h: "خدمات Valorant", items: ["شحن","بطاقة شحن","حساب"] } ] },
  "games__ea-sports-fc": { icon: "fas fa-gamepad", g1: "#F43F5E", g2: "#FB923C", order: 50, section: "games", sectionTitle: "🎮 شحن الألعاب",
    title: "EA Sports FC", intro: "كل خدمات EA Sports FC في مكان واحد — جودة عالية وتنفيذ آمن.",
    groups: [ { h: "خدمات EA Sports FC", items: ["شحن","بطاقة شحن","حساب"] } ] },
  "games__roblox": { icon: "fas fa-gamepad", g1: "#F43F5E", g2: "#FB923C", order: 51, section: "games", sectionTitle: "🎮 شحن الألعاب",
    title: "Roblox", intro: "كل خدمات Roblox في مكان واحد — جودة عالية وتنفيذ آمن.",
    groups: [ { h: "خدمات Roblox", items: ["شحن","بطاقة شحن","حساب"] } ] },
  "games__league-of-legends": { icon: "fas fa-gamepad", g1: "#F43F5E", g2: "#FB923C", order: 52, section: "games", sectionTitle: "🎮 شحن الألعاب",
    title: "League of Legends", intro: "كل خدمات League of Legends في مكان واحد — جودة عالية وتنفيذ آمن.",
    groups: [ { h: "خدمات League of Legends", items: ["شحن","بطاقة شحن","حساب"] } ] },
  "games__call-of-duty": { icon: "fas fa-gamepad", g1: "#F43F5E", g2: "#FB923C", order: 53, section: "games", sectionTitle: "🎮 شحن الألعاب",
    title: "Call of Duty", intro: "كل خدمات Call of Duty في مكان واحد — جودة عالية وتنفيذ آمن.",
    groups: [ { h: "خدمات Call of Duty", items: ["شحن","بطاقة شحن","حساب"] } ] },
  "games__clash-of-clans": { icon: "fas fa-gamepad", g1: "#F43F5E", g2: "#FB923C", order: 54, section: "games", sectionTitle: "🎮 شحن الألعاب",
    title: "Clash of Clans", intro: "كل خدمات Clash of Clans في مكان واحد — جودة عالية وتنفيذ آمن.",
    groups: [ { h: "خدمات Clash of Clans", items: ["شحن","بطاقة شحن","حساب"] } ] },
  "games__clash-royale": { icon: "fas fa-gamepad", g1: "#F43F5E", g2: "#FB923C", order: 55, section: "games", sectionTitle: "🎮 شحن الألعاب",
    title: "Clash Royale", intro: "كل خدمات Clash Royale في مكان واحد — جودة عالية وتنفيذ آمن.",
    groups: [ { h: "خدمات Clash Royale", items: ["شحن","بطاقة شحن","حساب"] } ] },
  "games__brawl-stars": { icon: "fas fa-gamepad", g1: "#F43F5E", g2: "#FB923C", order: 56, section: "games", sectionTitle: "🎮 شحن الألعاب",
    title: "Brawl Stars", intro: "كل خدمات Brawl Stars في مكان واحد — جودة عالية وتنفيذ آمن.",
    groups: [ { h: "خدمات Brawl Stars", items: ["شحن","بطاقة شحن","حساب"] } ] },
  "games__steam": { icon: "fab fa-steam", g1: "#F43F5E", g2: "#FB923C", order: 57, section: "games", sectionTitle: "🎮 شحن الألعاب",
    title: "Steam", intro: "كل خدمات Steam في مكان واحد — جودة عالية وتنفيذ آمن.",
    groups: [ { h: "خدمات Steam", items: ["شحن","بطاقة شحن","حساب"] } ] },
  "games__playstation": { icon: "fab fa-playstation", g1: "#F43F5E", g2: "#FB923C", order: 58, section: "games", sectionTitle: "🎮 شحن الألعاب",
    title: "PlayStation", intro: "كل خدمات PlayStation في مكان واحد — جودة عالية وتنفيذ آمن.",
    groups: [ { h: "خدمات PlayStation", items: ["شحن","بطاقة شحن","حساب"] } ] },
  "games__xbox": { icon: "fab fa-xbox", g1: "#F43F5E", g2: "#FB923C", order: 59, section: "games", sectionTitle: "🎮 شحن الألعاب",
    title: "Xbox", intro: "كل خدمات Xbox في مكان واحد — جودة عالية وتنفيذ آمن.",
    groups: [ { h: "خدمات Xbox", items: ["شحن","بطاقة شحن","حساب"] } ] },
  "games__nintendo": { icon: "fas fa-gamepad", g1: "#F43F5E", g2: "#FB923C", order: 60, section: "games", sectionTitle: "🎮 شحن الألعاب",
    title: "Nintendo", intro: "كل خدمات Nintendo في مكان واحد — جودة عالية وتنفيذ آمن.",
    groups: [ { h: "خدمات Nintendo", items: ["شحن","بطاقة شحن","حساب"] } ] },
  "dev__x": { icon: "fas fa-code", g1: "#0EA5E9", g2: "#2563EB", order: 61, section: "dev", sectionTitle: "💻 البرمجة والتطوير",
    title: "مواقع ويب", intro: "كل خدمات مواقع ويب في مكان واحد — جودة عالية وتنفيذ آمن.",
    groups: [ { h: "خدمات مواقع ويب", items: ["تنفيذ مشروع","استضافة","دعم فني"] } ] },
  "dev__x-2": { icon: "fas fa-code", g1: "#0EA5E9", g2: "#2563EB", order: 62, section: "dev", sectionTitle: "💻 البرمجة والتطوير",
    title: "تطبيقات موبايل", intro: "كل خدمات تطبيقات موبايل في مكان واحد — جودة عالية وتنفيذ آمن.",
    groups: [ { h: "خدمات تطبيقات موبايل", items: ["تنفيذ مشروع","استضافة","دعم فني"] } ] },
  "dev__x-3": { icon: "fas fa-code", g1: "#0EA5E9", g2: "#2563EB", order: 63, section: "dev", sectionTitle: "💻 البرمجة والتطوير",
    title: "بوتات تيليجرام", intro: "كل خدمات بوتات تيليجرام في مكان واحد — جودة عالية وتنفيذ آمن.",
    groups: [ { h: "خدمات بوتات تيليجرام", items: ["تنفيذ مشروع","استضافة","دعم فني"] } ] },
  "dev__x-4": { icon: "fas fa-code", g1: "#0EA5E9", g2: "#2563EB", order: 64, section: "dev", sectionTitle: "💻 البرمجة والتطوير",
    title: "بوتات واتساب", intro: "كل خدمات بوتات واتساب في مكان واحد — جودة عالية وتنفيذ آمن.",
    groups: [ { h: "خدمات بوتات واتساب", items: ["تنفيذ مشروع","استضافة","دعم فني"] } ] },
  "dev__x-5": { icon: "fas fa-code", g1: "#0EA5E9", g2: "#2563EB", order: 65, section: "dev", sectionTitle: "💻 البرمجة والتطوير",
    title: "بوتات ديسكورد", intro: "كل خدمات بوتات ديسكورد في مكان واحد — جودة عالية وتنفيذ آمن.",
    groups: [ { h: "خدمات بوتات ديسكورد", items: ["تنفيذ مشروع","استضافة","دعم فني"] } ] },
  "dev__apis": { icon: "fas fa-code", g1: "#0EA5E9", g2: "#2563EB", order: 66, section: "dev", sectionTitle: "💻 البرمجة والتطوير",
    title: "APIs", intro: "كل خدمات APIs في مكان واحد — جودة عالية وتنفيذ آمن.",
    groups: [ { h: "خدمات APIs", items: ["تنفيذ مشروع","استضافة","دعم فني"] } ] },
  "dev__web-automation": { icon: "fas fa-code", g1: "#0EA5E9", g2: "#2563EB", order: 67, section: "dev", sectionTitle: "💻 البرمجة والتطوير",
    title: "Web Automation", intro: "كل خدمات Web Automation في مكان واحد — جودة عالية وتنفيذ آمن.",
    groups: [ { h: "خدمات Web Automation", items: ["تنفيذ مشروع","استضافة","دعم فني"] } ] },
  "dev__ai-automation": { icon: "fas fa-code", g1: "#0EA5E9", g2: "#2563EB", order: 68, section: "dev", sectionTitle: "💻 البرمجة والتطوير",
    title: "AI Automation", intro: "كل خدمات AI Automation في مكان واحد — جودة عالية وتنفيذ آمن.",
    groups: [ { h: "خدمات AI Automation", items: ["تنفيذ مشروع","استضافة","دعم فني"] } ] },
  "dev__github": { icon: "fab fa-github", g1: "#0EA5E9", g2: "#2563EB", order: 69, section: "dev", sectionTitle: "💻 البرمجة والتطوير",
    title: "GitHub", intro: "كل خدمات GitHub في مكان واحد — جودة عالية وتنفيذ آمن.",
    groups: [ { h: "خدمات GitHub", items: ["تنفيذ مشروع","استضافة","دعم فني"] } ] },
  "dev__gitlab": { icon: "fab fa-gitlab", g1: "#0EA5E9", g2: "#2563EB", order: 70, section: "dev", sectionTitle: "💻 البرمجة والتطوير",
    title: "GitLab", intro: "كل خدمات GitLab في مكان واحد — جودة عالية وتنفيذ آمن.",
    groups: [ { h: "خدمات GitLab", items: ["تنفيذ مشروع","استضافة","دعم فني"] } ] },
  "dev__docker": { icon: "fab fa-docker", g1: "#0EA5E9", g2: "#2563EB", order: 71, section: "dev", sectionTitle: "💻 البرمجة والتطوير",
    title: "Docker", intro: "كل خدمات Docker في مكان واحد — جودة عالية وتنفيذ آمن.",
    groups: [ { h: "خدمات Docker", items: ["تنفيذ مشروع","استضافة","دعم فني"] } ] },
  "dev__vps": { icon: "fas fa-code", g1: "#0EA5E9", g2: "#2563EB", order: 72, section: "dev", sectionTitle: "💻 البرمجة والتطوير",
    title: "VPS", intro: "كل خدمات VPS في مكان واحد — جودة عالية وتنفيذ آمن.",
    groups: [ { h: "خدمات VPS", items: ["تنفيذ مشروع","استضافة","دعم فني"] } ] },
  "dev__cloud-hosting": { icon: "fas fa-code", g1: "#0EA5E9", g2: "#2563EB", order: 73, section: "dev", sectionTitle: "💻 البرمجة والتطوير",
    title: "Cloud Hosting", intro: "كل خدمات Cloud Hosting في مكان واحد — جودة عالية وتنفيذ آمن.",
    groups: [ { h: "خدمات Cloud Hosting", items: ["تنفيذ مشروع","استضافة","دعم فني"] } ] },
  "dev__firebase": { icon: "fas fa-code", g1: "#0EA5E9", g2: "#2563EB", order: 74, section: "dev", sectionTitle: "💻 البرمجة والتطوير",
    title: "Firebase", intro: "كل خدمات Firebase في مكان واحد — جودة عالية وتنفيذ آمن.",
    groups: [ { h: "خدمات Firebase", items: ["تنفيذ مشروع","استضافة","دعم فني"] } ] },
  "montage__x": { icon: "fas fa-film", g1: "#E0208F", g2: "#7C3AED", order: 75, section: "montage", sectionTitle: "🎬 المونتاج وتصميم الفيديو",
    title: "مونتاج فيديو", intro: "كل خدمات مونتاج فيديو في مكان واحد — جودة عالية وتنفيذ آمن.",
    groups: [ { h: "خدمات مونتاج فيديو", items: ["مونتاج فيديو","مونتاج ريلز","مونتاج إعلان"] } ] },
  "montage__x-2": { icon: "fas fa-film", g1: "#E0208F", g2: "#7C3AED", order: 76, section: "montage", sectionTitle: "🎬 المونتاج وتصميم الفيديو",
    title: "مونتاج ريلز وشورتس", intro: "كل خدمات مونتاج ريلز وشورتس في مكان واحد — جودة عالية وتنفيذ آمن.",
    groups: [ { h: "خدمات مونتاج ريلز وشورتس", items: ["مونتاج فيديو","مونتاج ريلز","مونتاج إعلان"] } ] },
  "montage__x-3": { icon: "fas fa-film", g1: "#E0208F", g2: "#7C3AED", order: 77, section: "montage", sectionTitle: "🎬 المونتاج وتصميم الفيديو",
    title: "مونتاج إعلانات", intro: "كل خدمات مونتاج إعلانات في مكان واحد — جودة عالية وتنفيذ آمن.",
    groups: [ { h: "خدمات مونتاج إعلانات", items: ["مونتاج فيديو","مونتاج ريلز","مونتاج إعلان"] } ] },
  "montage__x-4": { icon: "fas fa-film", g1: "#E0208F", g2: "#7C3AED", order: 78, section: "montage", sectionTitle: "🎬 المونتاج وتصميم الفيديو",
    title: "تصحيح ألوان", intro: "كل خدمات تصحيح ألوان في مكان واحد — جودة عالية وتنفيذ آمن.",
    groups: [ { h: "خدمات تصحيح ألوان", items: ["مونتاج فيديو","مونتاج ريلز","مونتاج إعلان"] } ] },
  "montage__x-5": { icon: "fas fa-film", g1: "#E0208F", g2: "#7C3AED", order: 79, section: "montage", sectionTitle: "🎬 المونتاج وتصميم الفيديو",
    title: "موشن جرافيك", intro: "كل خدمات موشن جرافيك في مكان واحد — جودة عالية وتنفيذ آمن.",
    groups: [ { h: "خدمات موشن جرافيك", items: ["مونتاج فيديو","مونتاج ريلز","مونتاج إعلان"] } ] },
  "montage__x-6": { icon: "fas fa-film", g1: "#E0208F", g2: "#7C3AED", order: 80, section: "montage", sectionTitle: "🎬 المونتاج وتصميم الفيديو",
    title: "ترجمة وسبتايتل", intro: "كل خدمات ترجمة وسبتايتل في مكان واحد — جودة عالية وتنفيذ آمن.",
    groups: [ { h: "خدمات ترجمة وسبتايتل", items: ["مونتاج فيديو","مونتاج ريلز","مونتاج إعلان"] } ] },
  "montage__x-7": { icon: "fas fa-film", g1: "#E0208F", g2: "#7C3AED", order: 81, section: "montage", sectionTitle: "🎬 المونتاج وتصميم الفيديو",
    title: "مونتاج بودكاست", intro: "كل خدمات مونتاج بودكاست في مكان واحد — جودة عالية وتنفيذ آمن.",
    groups: [ { h: "خدمات مونتاج بودكاست", items: ["مونتاج فيديو","مونتاج ريلز","مونتاج إعلان"] } ] },
  "montage__x-8": { icon: "fas fa-film", g1: "#E0208F", g2: "#7C3AED", order: 82, section: "montage", sectionTitle: "🎬 المونتاج وتصميم الفيديو",
    title: "تحسين جودة الفيديو", intro: "كل خدمات تحسين جودة الفيديو في مكان واحد — جودة عالية وتنفيذ آمن.",
    groups: [ { h: "خدمات تحسين جودة الفيديو", items: ["مونتاج فيديو","مونتاج ريلز","مونتاج إعلان"] } ] },
  "music__spotify": { icon: "fab fa-spotify", g1: "#1DB954", g2: "#059669", order: 83, section: "music", sectionTitle: "🎵 منصات الموسيقى",
    title: "Spotify", intro: "كل خدمات Spotify في مكان واحد — جودة عالية وتنفيذ آمن.",
    groups: [ { h: "خدمات Spotify", items: ["مستمعين","متابعين","تشغيلات","حفظ"] } ] },
  "music__soundcloud": { icon: "fab fa-soundcloud", g1: "#1DB954", g2: "#059669", order: 84, section: "music", sectionTitle: "🎵 منصات الموسيقى",
    title: "SoundCloud", intro: "كل خدمات SoundCloud في مكان واحد — جودة عالية وتنفيذ آمن.",
    groups: [ { h: "خدمات SoundCloud", items: ["مستمعين","متابعين","تشغيلات","حفظ"] } ] },
  "music__anghami": { icon: "fas fa-music", g1: "#1DB954", g2: "#059669", order: 85, section: "music", sectionTitle: "🎵 منصات الموسيقى",
    title: "Anghami", intro: "كل خدمات Anghami في مكان واحد — جودة عالية وتنفيذ آمن.",
    groups: [ { h: "خدمات Anghami", items: ["مستمعين","متابعين","تشغيلات","حفظ"] } ] },
  "music__deezer": { icon: "fab fa-deezer", g1: "#1DB954", g2: "#059669", order: 86, section: "music", sectionTitle: "🎵 منصات الموسيقى",
    title: "Deezer", intro: "كل خدمات Deezer في مكان واحد — جودة عالية وتنفيذ آمن.",
    groups: [ { h: "خدمات Deezer", items: ["مستمعين","متابعين","تشغيلات","حفظ"] } ] },
  "music__apple-music": { icon: "fas fa-music", g1: "#1DB954", g2: "#059669", order: 87, section: "music", sectionTitle: "🎵 منصات الموسيقى",
    title: "Apple Music", intro: "كل خدمات Apple Music في مكان واحد — جودة عالية وتنفيذ آمن.",
    groups: [ { h: "خدمات Apple Music", items: ["مستمعين","متابعين","تشغيلات","حفظ"] } ] },
  "music__youtube-music": { icon: "fas fa-music", g1: "#1DB954", g2: "#059669", order: 88, section: "music", sectionTitle: "🎵 منصات الموسيقى",
    title: "YouTube Music", intro: "كل خدمات YouTube Music في مكان واحد — جودة عالية وتنفيذ آمن.",
    groups: [ { h: "خدمات YouTube Music", items: ["مستمعين","متابعين","تشغيلات","حفظ"] } ] },
  "music__audiomack": { icon: "fas fa-music", g1: "#1DB954", g2: "#059669", order: 89, section: "music", sectionTitle: "🎵 منصات الموسيقى",
    title: "Audiomack", intro: "كل خدمات Audiomack في مكان واحد — جودة عالية وتنفيذ آمن.",
    groups: [ { h: "خدمات Audiomack", items: ["مستمعين","متابعين","تشغيلات","حفظ"] } ] },
  "music__boomplay": { icon: "fas fa-music", g1: "#1DB954", g2: "#059669", order: 90, section: "music", sectionTitle: "🎵 منصات الموسيقى",
    title: "Boomplay", intro: "كل خدمات Boomplay في مكان واحد — جودة عالية وتنفيذ آمن.",
    groups: [ { h: "خدمات Boomplay", items: ["مستمعين","متابعين","تشغيلات","حفظ"] } ] },
  "music__tidal": { icon: "fas fa-music", g1: "#1DB954", g2: "#059669", order: 91, section: "music", sectionTitle: "🎵 منصات الموسيقى",
    title: "Tidal", intro: "كل خدمات Tidal في مكان واحد — جودة عالية وتنفيذ آمن.",
    groups: [ { h: "خدمات Tidal", items: ["مستمعين","متابعين","تشغيلات","حفظ"] } ] },
  "music__amazon-music": { icon: "fas fa-music", g1: "#1DB954", g2: "#059669", order: 92, section: "music", sectionTitle: "🎵 منصات الموسيقى",
    title: "Amazon Music", intro: "كل خدمات Amazon Music في مكان واحد — جودة عالية وتنفيذ آمن.",
    groups: [ { h: "خدمات Amazon Music", items: ["مستمعين","متابعين","تشغيلات","حفظ"] } ] },
  "video__youtube": { icon: "fab fa-youtube", g1: "#EF4444", g2: "#B91C1C", order: 93, section: "video", sectionTitle: "🎞️ منصات الفيديو والبث",
    title: "YouTube", intro: "كل خدمات YouTube في مكان واحد — جودة عالية وتنفيذ آمن.",
    groups: [ { h: "خدمات YouTube", items: ["مشاهدات","مشتركين","اشتراك"] } ] },
  "video__vimeo": { icon: "fab fa-vimeo", g1: "#EF4444", g2: "#B91C1C", order: 94, section: "video", sectionTitle: "🎞️ منصات الفيديو والبث",
    title: "Vimeo", intro: "كل خدمات Vimeo في مكان واحد — جودة عالية وتنفيذ آمن.",
    groups: [ { h: "خدمات Vimeo", items: ["مشاهدات","مشتركين","اشتراك"] } ] },
  "video__dailymotion": { icon: "fas fa-clapperboard", g1: "#EF4444", g2: "#B91C1C", order: 95, section: "video", sectionTitle: "🎞️ منصات الفيديو والبث",
    title: "Dailymotion", intro: "كل خدمات Dailymotion في مكان واحد — جودة عالية وتنفيذ آمن.",
    groups: [ { h: "خدمات Dailymotion", items: ["مشاهدات","مشتركين","اشتراك"] } ] },
  "video__twitch": { icon: "fab fa-twitch", g1: "#EF4444", g2: "#B91C1C", order: 96, section: "video", sectionTitle: "🎞️ منصات الفيديو والبث",
    title: "Twitch", intro: "كل خدمات Twitch في مكان واحد — جودة عالية وتنفيذ آمن.",
    groups: [ { h: "خدمات Twitch", items: ["مشاهدات","مشتركين","اشتراك"] } ] },
  "video__kick": { icon: "fas fa-clapperboard", g1: "#EF4444", g2: "#B91C1C", order: 97, section: "video", sectionTitle: "🎞️ منصات الفيديو والبث",
    title: "Kick", intro: "كل خدمات Kick في مكان واحد — جودة عالية وتنفيذ آمن.",
    groups: [ { h: "خدمات Kick", items: ["مشاهدات","مشتركين","اشتراك"] } ] },
  "video__bigo-live": { icon: "fas fa-clapperboard", g1: "#EF4444", g2: "#B91C1C", order: 98, section: "video", sectionTitle: "🎞️ منصات الفيديو والبث",
    title: "Bigo Live", intro: "كل خدمات Bigo Live في مكان واحد — جودة عالية وتنفيذ آمن.",
    groups: [ { h: "خدمات Bigo Live", items: ["مشاهدات","مشتركين","اشتراك"] } ] },
  "video__likee": { icon: "fas fa-clapperboard", g1: "#EF4444", g2: "#B91C1C", order: 99, section: "video", sectionTitle: "🎞️ منصات الفيديو والبث",
    title: "Likee", intro: "كل خدمات Likee في مكان واحد — جودة عالية وتنفيذ آمن.",
    groups: [ { h: "خدمات Likee", items: ["مشاهدات","مشتركين","اشتراك"] } ] },
  "video__kwai": { icon: "fas fa-clapperboard", g1: "#EF4444", g2: "#B91C1C", order: 100, section: "video", sectionTitle: "🎞️ منصات الفيديو والبث",
    title: "Kwai", intro: "كل خدمات Kwai في مكان واحد — جودة عالية وتنفيذ آمن.",
    groups: [ { h: "خدمات Kwai", items: ["مشاهدات","مشتركين","اشتراك"] } ] },
  "video__rumble": { icon: "fas fa-clapperboard", g1: "#EF4444", g2: "#B91C1C", order: 101, section: "video", sectionTitle: "🎞️ منصات الفيديو والبث",
    title: "Rumble", intro: "كل خدمات Rumble في مكان واحد — جودة عالية وتنفيذ آمن.",
    groups: [ { h: "خدمات Rumble", items: ["مشاهدات","مشتركين","اشتراك"] } ] },
  "video__netflix": { icon: "fas fa-clapperboard", g1: "#EF4444", g2: "#B91C1C", order: 102, section: "video", sectionTitle: "🎞️ منصات الفيديو والبث",
    title: "Netflix", intro: "كل خدمات Netflix في مكان واحد — جودة عالية وتنفيذ آمن.",
    groups: [ { h: "خدمات Netflix", items: ["مشاهدات","مشتركين","اشتراك"] } ] },
  "video__shahid": { icon: "fas fa-clapperboard", g1: "#EF4444", g2: "#B91C1C", order: 103, section: "video", sectionTitle: "🎞️ منصات الفيديو والبث",
    title: "Shahid", intro: "كل خدمات Shahid في مكان واحد — جودة عالية وتنفيذ آمن.",
    groups: [ { h: "خدمات Shahid", items: ["مشاهدات","مشتركين","اشتراك"] } ] },
  "video__disney": { icon: "fas fa-clapperboard", g1: "#EF4444", g2: "#B91C1C", order: 104, section: "video", sectionTitle: "🎞️ منصات الفيديو والبث",
    title: "Disney+", intro: "كل خدمات Disney+ في مكان واحد — جودة عالية وتنفيذ آمن.",
    groups: [ { h: "خدمات Disney+", items: ["مشاهدات","مشتركين","اشتراك"] } ] },
  "video__prime-video": { icon: "fas fa-clapperboard", g1: "#EF4444", g2: "#B91C1C", order: 105, section: "video", sectionTitle: "🎞️ منصات الفيديو والبث",
    title: "Prime Video", intro: "كل خدمات Prime Video في مكان واحد — جودة عالية وتنفيذ آمن.",
    groups: [ { h: "خدمات Prime Video", items: ["مشاهدات","مشتركين","اشتراك"] } ] },
  "video__osn": { icon: "fas fa-clapperboard", g1: "#EF4444", g2: "#B91C1C", order: 106, section: "video", sectionTitle: "🎞️ منصات الفيديو والبث",
    title: "OSN+", intro: "كل خدمات OSN+ في مكان واحد — جودة عالية وتنفيذ آمن.",
    groups: [ { h: "خدمات OSN+", items: ["مشاهدات","مشتركين","اشتراك"] } ] },
  "video__watch-it": { icon: "fas fa-clapperboard", g1: "#EF4444", g2: "#B91C1C", order: 107, section: "video", sectionTitle: "🎞️ منصات الفيديو والبث",
    title: "Watch It", intro: "كل خدمات Watch It في مكان واحد — جودة عالية وتنفيذ آمن.",
    groups: [ { h: "خدمات Watch It", items: ["مشاهدات","مشتركين","اشتراك"] } ] },
  "email__gmail": { icon: "fas fa-envelope", g1: "#F59E0B", g2: "#D97706", order: 108, section: "email", sectionTitle: "📧 البريد الإلكتروني",
    title: "Gmail", intro: "كل خدمات Gmail في مكان واحد — جودة عالية وتنفيذ آمن.",
    groups: [ { h: "خدمات Gmail", items: ["حساب جاهز","إنشاء بريد"] } ] },
  "email__outlook": { icon: "fas fa-envelope", g1: "#F59E0B", g2: "#D97706", order: 109, section: "email", sectionTitle: "📧 البريد الإلكتروني",
    title: "Outlook", intro: "كل خدمات Outlook في مكان واحد — جودة عالية وتنفيذ آمن.",
    groups: [ { h: "خدمات Outlook", items: ["حساب جاهز","إنشاء بريد"] } ] },
  "email__yahoo": { icon: "fas fa-envelope", g1: "#F59E0B", g2: "#D97706", order: 110, section: "email", sectionTitle: "📧 البريد الإلكتروني",
    title: "Yahoo", intro: "كل خدمات Yahoo في مكان واحد — جودة عالية وتنفيذ آمن.",
    groups: [ { h: "خدمات Yahoo", items: ["حساب جاهز","إنشاء بريد"] } ] },
  "email__proton-mail": { icon: "fas fa-envelope", g1: "#F59E0B", g2: "#D97706", order: 111, section: "email", sectionTitle: "📧 البريد الإلكتروني",
    title: "Proton Mail", intro: "كل خدمات Proton Mail في مكان واحد — جودة عالية وتنفيذ آمن.",
    groups: [ { h: "خدمات Proton Mail", items: ["حساب جاهز","إنشاء بريد"] } ] },
  "email__zoho-mail": { icon: "fas fa-envelope", g1: "#F59E0B", g2: "#D97706", order: 112, section: "email", sectionTitle: "📧 البريد الإلكتروني",
    title: "Zoho Mail", intro: "كل خدمات Zoho Mail في مكان واحد — جودة عالية وتنفيذ آمن.",
    groups: [ { h: "خدمات Zoho Mail", items: ["حساب جاهز","إنشاء بريد"] } ] },
  "email__microsoft-365": { icon: "fas fa-envelope", g1: "#F59E0B", g2: "#D97706", order: 113, section: "email", sectionTitle: "📧 البريد الإلكتروني",
    title: "Microsoft 365", intro: "كل خدمات Microsoft 365 في مكان واحد — جودة عالية وتنفيذ آمن.",
    groups: [ { h: "خدمات Microsoft 365", items: ["حساب جاهز","إنشاء بريد"] } ] },
  "email__google-workspace": { icon: "fas fa-envelope", g1: "#F59E0B", g2: "#D97706", order: 114, section: "email", sectionTitle: "📧 البريد الإلكتروني",
    title: "Google Workspace", intro: "كل خدمات Google Workspace في مكان واحد — جودة عالية وتنفيذ آمن.",
    groups: [ { h: "خدمات Google Workspace", items: ["حساب جاهز","إنشاء بريد"] } ] },
  "cloud__google-drive": { icon: "fas fa-cloud", g1: "#38BDF8", g2: "#0284C7", order: 115, section: "cloud", sectionTitle: "☁️ التخزين السحابي",
    title: "Google Drive", intro: "كل خدمات Google Drive في مكان واحد — جودة عالية وتنفيذ آمن.",
    groups: [ { h: "خدمات Google Drive", items: ["مساحة تخزين","اشتراك"] } ] },
  "cloud__dropbox": { icon: "fab fa-dropbox", g1: "#38BDF8", g2: "#0284C7", order: 116, section: "cloud", sectionTitle: "☁️ التخزين السحابي",
    title: "Dropbox", intro: "كل خدمات Dropbox في مكان واحد — جودة عالية وتنفيذ آمن.",
    groups: [ { h: "خدمات Dropbox", items: ["مساحة تخزين","اشتراك"] } ] },
  "cloud__onedrive": { icon: "fas fa-cloud", g1: "#38BDF8", g2: "#0284C7", order: 117, section: "cloud", sectionTitle: "☁️ التخزين السحابي",
    title: "OneDrive", intro: "كل خدمات OneDrive في مكان واحد — جودة عالية وتنفيذ آمن.",
    groups: [ { h: "خدمات OneDrive", items: ["مساحة تخزين","اشتراك"] } ] },
  "cloud__mega": { icon: "fas fa-cloud", g1: "#38BDF8", g2: "#0284C7", order: 118, section: "cloud", sectionTitle: "☁️ التخزين السحابي",
    title: "MEGA", intro: "كل خدمات MEGA في مكان واحد — جودة عالية وتنفيذ آمن.",
    groups: [ { h: "خدمات MEGA", items: ["مساحة تخزين","اشتراك"] } ] },
  "cloud__icloud": { icon: "fas fa-cloud", g1: "#38BDF8", g2: "#0284C7", order: 119, section: "cloud", sectionTitle: "☁️ التخزين السحابي",
    title: "iCloud", intro: "كل خدمات iCloud في مكان واحد — جودة عالية وتنفيذ آمن.",
    groups: [ { h: "خدمات iCloud", items: ["مساحة تخزين","اشتراك"] } ] },
  "cloud__box": { icon: "fas fa-cloud", g1: "#38BDF8", g2: "#0284C7", order: 120, section: "cloud", sectionTitle: "☁️ التخزين السحابي",
    title: "Box", intro: "كل خدمات Box في مكان واحد — جودة عالية وتنفيذ آمن.",
    groups: [ { h: "خدمات Box", items: ["مساحة تخزين","اشتراك"] } ] },
  "cloud__pcloud": { icon: "fas fa-cloud", g1: "#38BDF8", g2: "#0284C7", order: 121, section: "cloud", sectionTitle: "☁️ التخزين السحابي",
    title: "pCloud", intro: "كل خدمات pCloud في مكان واحد — جودة عالية وتنفيذ آمن.",
    groups: [ { h: "خدمات pCloud", items: ["مساحة تخزين","اشتراك"] } ] },
  "web__x": { icon: "fas fa-globe", g1: "#14B8A6", g2: "#0D9488", order: 122, section: "web", sectionTitle: "🌐 المواقع والمتاجر",
    title: "تصميم مواقع", intro: "كل خدمات تصميم مواقع في مكان واحد — جودة عالية وتنفيذ آمن.",
    groups: [ { h: "خدمات تصميم مواقع", items: ["تنفيذ","اشتراك","دعم"] } ] },
  "web__x-2": { icon: "fas fa-globe", g1: "#14B8A6", g2: "#0D9488", order: 123, section: "web", sectionTitle: "🌐 المواقع والمتاجر",
    title: "تصميم متاجر", intro: "كل خدمات تصميم متاجر في مكان واحد — جودة عالية وتنفيذ آمن.",
    groups: [ { h: "خدمات تصميم متاجر", items: ["تنفيذ","اشتراك","دعم"] } ] },
  "web__wordpress": { icon: "fab fa-wordpress", g1: "#14B8A6", g2: "#0D9488", order: 124, section: "web", sectionTitle: "🌐 المواقع والمتاجر",
    title: "WordPress", intro: "كل خدمات WordPress في مكان واحد — جودة عالية وتنفيذ آمن.",
    groups: [ { h: "خدمات WordPress", items: ["تنفيذ","اشتراك","دعم"] } ] },
  "web__shopify": { icon: "fab fa-shopify", g1: "#14B8A6", g2: "#0D9488", order: 125, section: "web", sectionTitle: "🌐 المواقع والمتاجر",
    title: "Shopify", intro: "كل خدمات Shopify في مكان واحد — جودة عالية وتنفيذ آمن.",
    groups: [ { h: "خدمات Shopify", items: ["تنفيذ","اشتراك","دعم"] } ] },
  "web__woocommerce": { icon: "fas fa-globe", g1: "#14B8A6", g2: "#0D9488", order: 126, section: "web", sectionTitle: "🌐 المواقع والمتاجر",
    title: "WooCommerce", intro: "كل خدمات WooCommerce في مكان واحد — جودة عالية وتنفيذ آمن.",
    groups: [ { h: "خدمات WooCommerce", items: ["تنفيذ","اشتراك","دعم"] } ] },
  "web__wix": { icon: "fab fa-wix", g1: "#14B8A6", g2: "#0D9488", order: 127, section: "web", sectionTitle: "🌐 المواقع والمتاجر",
    title: "Wix", intro: "كل خدمات Wix في مكان واحد — جودة عالية وتنفيذ آمن.",
    groups: [ { h: "خدمات Wix", items: ["تنفيذ","اشتراك","دعم"] } ] },
  "web__webflow": { icon: "fab fa-webflow", g1: "#14B8A6", g2: "#0D9488", order: 128, section: "web", sectionTitle: "🌐 المواقع والمتاجر",
    title: "Webflow", intro: "كل خدمات Webflow في مكان واحد — جودة عالية وتنفيذ آمن.",
    groups: [ { h: "خدمات Webflow", items: ["تنفيذ","اشتراك","دعم"] } ] },
  "web__framer": { icon: "fas fa-globe", g1: "#14B8A6", g2: "#0D9488", order: 129, section: "web", sectionTitle: "🌐 المواقع والمتاجر",
    title: "Framer", intro: "كل خدمات Framer في مكان واحد — جودة عالية وتنفيذ آمن.",
    groups: [ { h: "خدمات Framer", items: ["تنفيذ","اشتراك","دعم"] } ] },
  "web__x-3": { icon: "fas fa-globe", g1: "#14B8A6", g2: "#0D9488", order: 130, section: "web", sectionTitle: "🌐 المواقع والمتاجر",
    title: "دومينات", intro: "كل خدمات دومينات في مكان واحد — جودة عالية وتنفيذ آمن.",
    groups: [ { h: "خدمات دومينات", items: ["تنفيذ","اشتراك","دعم"] } ] },
  "web__x-4": { icon: "fas fa-globe", g1: "#14B8A6", g2: "#0D9488", order: 131, section: "web", sectionTitle: "🌐 المواقع والمتاجر",
    title: "استضافة", intro: "كل خدمات استضافة في مكان واحد — جودة عالية وتنفيذ آمن.",
    groups: [ { h: "خدمات استضافة", items: ["تنفيذ","اشتراك","دعم"] } ] },
  "web__ssl": { icon: "fas fa-globe", g1: "#14B8A6", g2: "#0D9488", order: 132, section: "web", sectionTitle: "🌐 المواقع والمتاجر",
    title: "SSL", intro: "كل خدمات SSL في مكان واحد — جودة عالية وتنفيذ آمن.",
    groups: [ { h: "خدمات SSL", items: ["تنفيذ","اشتراك","دعم"] } ] },
  "ads__meta-ads": { icon: "fas fa-bullhorn", g1: "#6366F1", g2: "#4338CA", order: 133, section: "ads", sectionTitle: "📢 الإعلانات الممولة",
    title: "Meta Ads", intro: "كل خدمات Meta Ads في مكان واحد — جودة عالية وتنفيذ آمن.",
    groups: [ { h: "خدمات Meta Ads", items: ["إدارة حملة","شحن رصيد إعلاني"] } ] },
  "ads__google-ads": { icon: "fas fa-bullhorn", g1: "#6366F1", g2: "#4338CA", order: 134, section: "ads", sectionTitle: "📢 الإعلانات الممولة",
    title: "Google Ads", intro: "كل خدمات Google Ads في مكان واحد — جودة عالية وتنفيذ آمن.",
    groups: [ { h: "خدمات Google Ads", items: ["إدارة حملة","شحن رصيد إعلاني"] } ] },
  "ads__tiktok-ads": { icon: "fas fa-bullhorn", g1: "#6366F1", g2: "#4338CA", order: 135, section: "ads", sectionTitle: "📢 الإعلانات الممولة",
    title: "TikTok Ads", intro: "كل خدمات TikTok Ads في مكان واحد — جودة عالية وتنفيذ آمن.",
    groups: [ { h: "خدمات TikTok Ads", items: ["إدارة حملة","شحن رصيد إعلاني"] } ] },
  "ads__snapchat-ads": { icon: "fas fa-bullhorn", g1: "#6366F1", g2: "#4338CA", order: 136, section: "ads", sectionTitle: "📢 الإعلانات الممولة",
    title: "Snapchat Ads", intro: "كل خدمات Snapchat Ads في مكان واحد — جودة عالية وتنفيذ آمن.",
    groups: [ { h: "خدمات Snapchat Ads", items: ["إدارة حملة","شحن رصيد إعلاني"] } ] },
  "ads__x-ads": { icon: "fas fa-bullhorn", g1: "#6366F1", g2: "#4338CA", order: 137, section: "ads", sectionTitle: "📢 الإعلانات الممولة",
    title: "X Ads", intro: "كل خدمات X Ads في مكان واحد — جودة عالية وتنفيذ آمن.",
    groups: [ { h: "خدمات X Ads", items: ["إدارة حملة","شحن رصيد إعلاني"] } ] },
  "ads__linkedin-ads": { icon: "fas fa-bullhorn", g1: "#6366F1", g2: "#4338CA", order: 138, section: "ads", sectionTitle: "📢 الإعلانات الممولة",
    title: "LinkedIn Ads", intro: "كل خدمات LinkedIn Ads في مكان واحد — جودة عالية وتنفيذ آمن.",
    groups: [ { h: "خدمات LinkedIn Ads", items: ["إدارة حملة","شحن رصيد إعلاني"] } ] },
  "ads__youtube-ads": { icon: "fas fa-bullhorn", g1: "#6366F1", g2: "#4338CA", order: 139, section: "ads", sectionTitle: "📢 الإعلانات الممولة",
    title: "YouTube Ads", intro: "كل خدمات YouTube Ads في مكان واحد — جودة عالية وتنفيذ آمن.",
    groups: [ { h: "خدمات YouTube Ads", items: ["إدارة حملة","شحن رصيد إعلاني"] } ] },
  "ads__pinterest-ads": { icon: "fas fa-bullhorn", g1: "#6366F1", g2: "#4338CA", order: 140, section: "ads", sectionTitle: "📢 الإعلانات الممولة",
    title: "Pinterest Ads", intro: "كل خدمات Pinterest Ads في مكان واحد — جودة عالية وتنفيذ آمن.",
    groups: [ { h: "خدمات Pinterest Ads", items: ["إدارة حملة","شحن رصيد إعلاني"] } ] },
  "ads__reddit-ads": { icon: "fas fa-bullhorn", g1: "#6366F1", g2: "#4338CA", order: 141, section: "ads", sectionTitle: "📢 الإعلانات الممولة",
    title: "Reddit Ads", intro: "كل خدمات Reddit Ads في مكان واحد — جودة عالية وتنفيذ آمن.",
    groups: [ { h: "خدمات Reddit Ads", items: ["إدارة حملة","شحن رصيد إعلاني"] } ] },
  "trade__x": { icon: "fas fa-right-left", g1: "#F97316", g2: "#EA580C", order: 142, section: "trade", sectionTitle: "🛒 البيع والشراء",
    title: "بيع حسابات", intro: "كل خدمات بيع حسابات في مكان واحد — جودة عالية وتنفيذ آمن.",
    groups: [ { h: "خدمات بيع حسابات", items: ["بيع","شراء","وساطة آمنة"] } ] },
  "trade__x-2": { icon: "fas fa-right-left", g1: "#F97316", g2: "#EA580C", order: 143, section: "trade", sectionTitle: "🛒 البيع والشراء",
    title: "شراء حسابات", intro: "كل خدمات شراء حسابات في مكان واحد — جودة عالية وتنفيذ آمن.",
    groups: [ { h: "خدمات شراء حسابات", items: ["بيع","شراء","وساطة آمنة"] } ] },
  "trade__x-3": { icon: "fas fa-right-left", g1: "#F97316", g2: "#EA580C", order: 144, section: "trade", sectionTitle: "🛒 البيع والشراء",
    title: "صفحات", intro: "كل خدمات صفحات في مكان واحد — جودة عالية وتنفيذ آمن.",
    groups: [ { h: "خدمات صفحات", items: ["بيع","شراء","وساطة آمنة"] } ] },
  "trade__x-4": { icon: "fas fa-right-left", g1: "#F97316", g2: "#EA580C", order: 145, section: "trade", sectionTitle: "🛒 البيع والشراء",
    title: "قنوات", intro: "كل خدمات قنوات في مكان واحد — جودة عالية وتنفيذ آمن.",
    groups: [ { h: "خدمات قنوات", items: ["بيع","شراء","وساطة آمنة"] } ] },
  "trade__x-5": { icon: "fas fa-right-left", g1: "#F97316", g2: "#EA580C", order: 146, section: "trade", sectionTitle: "🛒 البيع والشراء",
    title: "مواقع", intro: "كل خدمات مواقع في مكان واحد — جودة عالية وتنفيذ آمن.",
    groups: [ { h: "خدمات مواقع", items: ["بيع","شراء","وساطة آمنة"] } ] },
  "trade__x-6": { icon: "fas fa-right-left", g1: "#F97316", g2: "#EA580C", order: 147, section: "trade", sectionTitle: "🛒 البيع والشراء",
    title: "دومينات", intro: "كل خدمات دومينات في مكان واحد — جودة عالية وتنفيذ آمن.",
    groups: [ { h: "خدمات دومينات", items: ["بيع","شراء","وساطة آمنة"] } ] },
  "trade__x-7": { icon: "fas fa-right-left", g1: "#F97316", g2: "#EA580C", order: 148, section: "trade", sectionTitle: "🛒 البيع والشراء",
    title: "تطبيقات", intro: "كل خدمات تطبيقات في مكان واحد — جودة عالية وتنفيذ آمن.",
    groups: [ { h: "خدمات تطبيقات", items: ["بيع","شراء","وساطة آمنة"] } ] },
  "trade__x-8": { icon: "fas fa-right-left", g1: "#F97316", g2: "#EA580C", order: 149, section: "trade", sectionTitle: "🛒 البيع والشراء",
    title: "بوتات", intro: "كل خدمات بوتات في مكان واحد — جودة عالية وتنفيذ آمن.",
    groups: [ { h: "خدمات بوتات", items: ["بيع","شراء","وساطة آمنة"] } ] },
  "trade__x-9": { icon: "fas fa-right-left", g1: "#F97316", g2: "#EA580C", order: 150, section: "trade", sectionTitle: "🛒 البيع والشراء",
    title: "جروبات", intro: "كل خدمات جروبات في مكان واحد — جودة عالية وتنفيذ آمن.",
    groups: [ { h: "خدمات جروبات", items: ["بيع","شراء","وساطة آمنة"] } ] },
  "trade__discord": { icon: "fas fa-right-left", g1: "#F97316", g2: "#EA580C", order: 151, section: "trade", sectionTitle: "🛒 البيع والشراء",
    title: "سيرفرات Discord", intro: "كل خدمات سيرفرات Discord في مكان واحد — جودة عالية وتنفيذ آمن.",
    groups: [ { h: "خدمات سيرفرات Discord", items: ["بيع","شراء","وساطة آمنة"] } ] },
  "trade__telegram": { icon: "fas fa-right-left", g1: "#F97316", g2: "#EA580C", order: 152, section: "trade", sectionTitle: "🛒 البيع والشراء",
    title: "سيرفرات Telegram", intro: "كل خدمات سيرفرات Telegram في مكان واحد — جودة عالية وتنفيذ آمن.",
    groups: [ { h: "خدمات سيرفرات Telegram", items: ["بيع","شراء","وساطة آمنة"] } ] },
  "verify__facebook": { icon: "fas fa-circle-check", g1: "#22C55E", g2: "#15803D", order: 153, section: "verify", sectionTitle: "✅ التوثيق الرسمي",
    title: "توثيق Facebook", intro: "كل خدمات توثيق Facebook في مكان واحد — جودة عالية وتنفيذ آمن.",
    groups: [ { h: "خدمات توثيق Facebook", items: ["توثيق الحساب"] } ] },
  "verify__instagram": { icon: "fas fa-circle-check", g1: "#22C55E", g2: "#15803D", order: 154, section: "verify", sectionTitle: "✅ التوثيق الرسمي",
    title: "توثيق Instagram", intro: "كل خدمات توثيق Instagram في مكان واحد — جودة عالية وتنفيذ آمن.",
    groups: [ { h: "خدمات توثيق Instagram", items: ["توثيق الحساب"] } ] },
  "verify__tiktok": { icon: "fas fa-circle-check", g1: "#22C55E", g2: "#15803D", order: 155, section: "verify", sectionTitle: "✅ التوثيق الرسمي",
    title: "توثيق TikTok", intro: "كل خدمات توثيق TikTok في مكان واحد — جودة عالية وتنفيذ آمن.",
    groups: [ { h: "خدمات توثيق TikTok", items: ["توثيق الحساب"] } ] },
  "verify__snapchat": { icon: "fas fa-circle-check", g1: "#22C55E", g2: "#15803D", order: 156, section: "verify", sectionTitle: "✅ التوثيق الرسمي",
    title: "توثيق Snapchat", intro: "كل خدمات توثيق Snapchat في مكان واحد — جودة عالية وتنفيذ آمن.",
    groups: [ { h: "خدمات توثيق Snapchat", items: ["توثيق الحساب"] } ] },
  "verify__x": { icon: "fas fa-circle-check", g1: "#22C55E", g2: "#15803D", order: 157, section: "verify", sectionTitle: "✅ التوثيق الرسمي",
    title: "توثيق X", intro: "كل خدمات توثيق X في مكان واحد — جودة عالية وتنفيذ آمن.",
    groups: [ { h: "خدمات توثيق X", items: ["توثيق الحساب"] } ] },
  "verify__whatsapp-business": { icon: "fas fa-circle-check", g1: "#22C55E", g2: "#15803D", order: 158, section: "verify", sectionTitle: "✅ التوثيق الرسمي",
    title: "WhatsApp Business", intro: "كل خدمات WhatsApp Business في مكان واحد — جودة عالية وتنفيذ آمن.",
    groups: [ { h: "خدمات WhatsApp Business", items: ["توثيق الحساب"] } ] },
  "verify__meta-verified": { icon: "fas fa-circle-check", g1: "#22C55E", g2: "#15803D", order: 159, section: "verify", sectionTitle: "✅ التوثيق الرسمي",
    title: "Meta Verified", intro: "كل خدمات Meta Verified في مكان واحد — جودة عالية وتنفيذ آمن.",
    groups: [ { h: "خدمات Meta Verified", items: ["توثيق الحساب"] } ] },
  "verify__youtube": { icon: "fas fa-circle-check", g1: "#22C55E", g2: "#15803D", order: 160, section: "verify", sectionTitle: "✅ التوثيق الرسمي",
    title: "توثيق YouTube", intro: "كل خدمات توثيق YouTube في مكان واحد — جودة عالية وتنفيذ آمن.",
    groups: [ { h: "خدمات توثيق YouTube", items: ["توثيق الحساب"] } ] },
  "verify__telegram": { icon: "fas fa-circle-check", g1: "#22C55E", g2: "#15803D", order: 161, section: "verify", sectionTitle: "✅ التوثيق الرسمي",
    title: "توثيق Telegram", intro: "كل خدمات توثيق Telegram في مكان واحد — جودة عالية وتنفيذ آمن.",
    groups: [ { h: "خدمات توثيق Telegram", items: ["توثيق الحساب"] } ] },
  "verify__linkedin": { icon: "fas fa-circle-check", g1: "#22C55E", g2: "#15803D", order: 162, section: "verify", sectionTitle: "✅ التوثيق الرسمي",
    title: "توثيق LinkedIn", intro: "كل خدمات توثيق LinkedIn في مكان واحد — جودة عالية وتنفيذ آمن.",
    groups: [ { h: "خدمات توثيق LinkedIn", items: ["توثيق الحساب"] } ] },
  "protect__x": { icon: "fas fa-shield-halved", g1: "#0EA5E9", g2: "#155E75", order: 163, section: "protect", sectionTitle: "🛡️ الحماية والاسترجاع",
    title: "استرجاع الحسابات", intro: "كل خدمات استرجاع الحسابات في مكان واحد — جودة عالية وتنفيذ آمن.",
    groups: [ { h: "خدمات استرجاع الحسابات", items: ["استرجاع","حماية"] } ] },
  "protect__x-2": { icon: "fas fa-shield-halved", g1: "#0EA5E9", g2: "#155E75", order: 164, section: "protect", sectionTitle: "🛡️ الحماية والاسترجاع",
    title: "استعادة الصفحات", intro: "كل خدمات استعادة الصفحات في مكان واحد — جودة عالية وتنفيذ آمن.",
    groups: [ { h: "خدمات استعادة الصفحات", items: ["استرجاع","حماية"] } ] },
  "protect__x-3": { icon: "fas fa-shield-halved", g1: "#0EA5E9", g2: "#155E75", order: 165, section: "protect", sectionTitle: "🛡️ الحماية والاسترجاع",
    title: "استعادة القنوات", intro: "كل خدمات استعادة القنوات في مكان واحد — جودة عالية وتنفيذ آمن.",
    groups: [ { h: "خدمات استعادة القنوات", items: ["استرجاع","حماية"] } ] },
  "protect__x-4": { icon: "fas fa-shield-halved", g1: "#0EA5E9", g2: "#155E75", order: 166, section: "protect", sectionTitle: "🛡️ الحماية والاسترجاع",
    title: "استعادة البريد", intro: "كل خدمات استعادة البريد في مكان واحد — جودة عالية وتنفيذ آمن.",
    groups: [ { h: "خدمات استعادة البريد", items: ["استرجاع","حماية"] } ] },
  "protect__x-5": { icon: "fas fa-shield-halved", g1: "#0EA5E9", g2: "#155E75", order: 167, section: "protect", sectionTitle: "🛡️ الحماية والاسترجاع",
    title: "فك التقييد", intro: "كل خدمات فك التقييد في مكان واحد — جودة عالية وتنفيذ آمن.",
    groups: [ { h: "خدمات فك التقييد", items: ["استرجاع","حماية"] } ] },
  "protect__x-6": { icon: "fas fa-shield-halved", g1: "#0EA5E9", g2: "#155E75", order: 168, section: "protect", sectionTitle: "🛡️ الحماية والاسترجاع",
    title: "إزالة الانتهاكات", intro: "كل خدمات إزالة الانتهاكات في مكان واحد — جودة عالية وتنفيذ آمن.",
    groups: [ { h: "خدمات إزالة الانتهاكات", items: ["استرجاع","حماية"] } ] },
  "protect__x-7": { icon: "fas fa-shield-halved", g1: "#0EA5E9", g2: "#155E75", order: 169, section: "protect", sectionTitle: "🛡️ الحماية والاسترجاع",
    title: "إزالة البلاغات", intro: "كل خدمات إزالة البلاغات في مكان واحد — جودة عالية وتنفيذ آمن.",
    groups: [ { h: "خدمات إزالة البلاغات", items: ["استرجاع","حماية"] } ] },
  "protect__x-8": { icon: "fas fa-shield-halved", g1: "#0EA5E9", g2: "#155E75", order: 170, section: "protect", sectionTitle: "🛡️ الحماية والاسترجاع",
    title: "تأمين الحسابات", intro: "كل خدمات تأمين الحسابات في مكان واحد — جودة عالية وتنفيذ آمن.",
    groups: [ { h: "خدمات تأمين الحسابات", items: ["استرجاع","حماية"] } ] },
  "smm__x": { icon: "fas fa-chart-line", g1: "#8B5CF6", g2: "#6D28D9", order: 171, section: "smm", sectionTitle: "📊 خدمات SMM",
    title: "متابعين", intro: "كل خدمات متابعين في مكان واحد — جودة عالية وتنفيذ آمن.",
    groups: [ { h: "خدمات متابعين", items: ["تنفيذ الخدمة"] } ] },
  "smm__x-2": { icon: "fas fa-chart-line", g1: "#8B5CF6", g2: "#6D28D9", order: 172, section: "smm", sectionTitle: "📊 خدمات SMM",
    title: "لايكات", intro: "كل خدمات لايكات في مكان واحد — جودة عالية وتنفيذ آمن.",
    groups: [ { h: "خدمات لايكات", items: ["تنفيذ الخدمة"] } ] },
  "smm__x-3": { icon: "fas fa-chart-line", g1: "#8B5CF6", g2: "#6D28D9", order: 173, section: "smm", sectionTitle: "📊 خدمات SMM",
    title: "مشاهدات", intro: "كل خدمات مشاهدات في مكان واحد — جودة عالية وتنفيذ آمن.",
    groups: [ { h: "خدمات مشاهدات", items: ["تنفيذ الخدمة"] } ] },
  "smm__x-4": { icon: "fas fa-chart-line", g1: "#8B5CF6", g2: "#6D28D9", order: 174, section: "smm", sectionTitle: "📊 خدمات SMM",
    title: "تعليقات", intro: "كل خدمات تعليقات في مكان واحد — جودة عالية وتنفيذ آمن.",
    groups: [ { h: "خدمات تعليقات", items: ["تنفيذ الخدمة"] } ] },
  "smm__x-5": { icon: "fas fa-chart-line", g1: "#8B5CF6", g2: "#6D28D9", order: 175, section: "smm", sectionTitle: "📊 خدمات SMM",
    title: "مشاركات", intro: "كل خدمات مشاركات في مكان واحد — جودة عالية وتنفيذ آمن.",
    groups: [ { h: "خدمات مشاركات", items: ["تنفيذ الخدمة"] } ] },
  "smm__x-6": { icon: "fas fa-chart-line", g1: "#8B5CF6", g2: "#6D28D9", order: 176, section: "smm", sectionTitle: "📊 خدمات SMM",
    title: "حفظ", intro: "كل خدمات حفظ في مكان واحد — جودة عالية وتنفيذ آمن.",
    groups: [ { h: "خدمات حفظ", items: ["تنفيذ الخدمة"] } ] },
  "smm__x-7": { icon: "fas fa-chart-line", g1: "#8B5CF6", g2: "#6D28D9", order: 177, section: "smm", sectionTitle: "📊 خدمات SMM",
    title: "ريتويت", intro: "كل خدمات ريتويت في مكان واحد — جودة عالية وتنفيذ آمن.",
    groups: [ { h: "خدمات ريتويت", items: ["تنفيذ الخدمة"] } ] },
  "smm__x-8": { icon: "fas fa-chart-line", g1: "#8B5CF6", g2: "#6D28D9", order: 178, section: "smm", sectionTitle: "📊 خدمات SMM",
    title: "ريلز", intro: "كل خدمات ريلز في مكان واحد — جودة عالية وتنفيذ آمن.",
    groups: [ { h: "خدمات ريلز", items: ["تنفيذ الخدمة"] } ] },
  "smm__x-9": { icon: "fas fa-chart-line", g1: "#8B5CF6", g2: "#6D28D9", order: 179, section: "smm", sectionTitle: "📊 خدمات SMM",
    title: "ستوري", intro: "كل خدمات ستوري في مكان واحد — جودة عالية وتنفيذ آمن.",
    groups: [ { h: "خدمات ستوري", items: ["تنفيذ الخدمة"] } ] },
  "smm__x-10": { icon: "fas fa-chart-line", g1: "#8B5CF6", g2: "#6D28D9", order: 180, section: "smm", sectionTitle: "📊 خدمات SMM",
    title: "بث مباشر", intro: "كل خدمات بث مباشر في مكان واحد — جودة عالية وتنفيذ آمن.",
    groups: [ { h: "خدمات بث مباشر", items: ["تنفيذ الخدمة"] } ] },
  "smm__x-11": { icon: "fas fa-chart-line", g1: "#8B5CF6", g2: "#6D28D9", order: 181, section: "smm", sectionTitle: "📊 خدمات SMM",
    title: "ساعات مشاهدة", intro: "كل خدمات ساعات مشاهدة في مكان واحد — جودة عالية وتنفيذ آمن.",
    groups: [ { h: "خدمات ساعات مشاهدة", items: ["تنفيذ الخدمة"] } ] },
  "smm__x-12": { icon: "fas fa-chart-line", g1: "#8B5CF6", g2: "#6D28D9", order: 182, section: "smm", sectionTitle: "📊 خدمات SMM",
    title: "أعضاء", intro: "كل خدمات أعضاء في مكان واحد — جودة عالية وتنفيذ آمن.",
    groups: [ { h: "خدمات أعضاء", items: ["تنفيذ الخدمة"] } ] },
  "smm__x-13": { icon: "fas fa-chart-line", g1: "#8B5CF6", g2: "#6D28D9", order: 183, section: "smm", sectionTitle: "📊 خدمات SMM",
    title: "تصويتات", intro: "كل خدمات تصويتات في مكان واحد — جودة عالية وتنفيذ آمن.",
    groups: [ { h: "خدمات تصويتات", items: ["تنفيذ الخدمة"] } ] },
  "subscriptions__netflix": { icon: "fas fa-credit-card", g1: "#EC4899", g2: "#BE185D", order: 184, section: "subscriptions", sectionTitle: "💳 الاشتراكات الرقمية",
    title: "Netflix", intro: "كل خدمات Netflix في مكان واحد — جودة عالية وتنفيذ آمن.",
    groups: [ { h: "خدمات Netflix", items: ["اشتراك شهري","اشتراك سنوي"] } ] },
  "subscriptions__shahid": { icon: "fas fa-credit-card", g1: "#EC4899", g2: "#BE185D", order: 185, section: "subscriptions", sectionTitle: "💳 الاشتراكات الرقمية",
    title: "Shahid", intro: "كل خدمات Shahid في مكان واحد — جودة عالية وتنفيذ آمن.",
    groups: [ { h: "خدمات Shahid", items: ["اشتراك شهري","اشتراك سنوي"] } ] },
  "subscriptions__osn": { icon: "fas fa-credit-card", g1: "#EC4899", g2: "#BE185D", order: 186, section: "subscriptions", sectionTitle: "💳 الاشتراكات الرقمية",
    title: "OSN+", intro: "كل خدمات OSN+ في مكان واحد — جودة عالية وتنفيذ آمن.",
    groups: [ { h: "خدمات OSN+", items: ["اشتراك شهري","اشتراك سنوي"] } ] },
  "subscriptions__disney": { icon: "fas fa-credit-card", g1: "#EC4899", g2: "#BE185D", order: 187, section: "subscriptions", sectionTitle: "💳 الاشتراكات الرقمية",
    title: "Disney+", intro: "كل خدمات Disney+ في مكان واحد — جودة عالية وتنفيذ آمن.",
    groups: [ { h: "خدمات Disney+", items: ["اشتراك شهري","اشتراك سنوي"] } ] },
  "subscriptions__spotify-premium": { icon: "fas fa-credit-card", g1: "#EC4899", g2: "#BE185D", order: 188, section: "subscriptions", sectionTitle: "💳 الاشتراكات الرقمية",
    title: "Spotify Premium", intro: "كل خدمات Spotify Premium في مكان واحد — جودة عالية وتنفيذ آمن.",
    groups: [ { h: "خدمات Spotify Premium", items: ["اشتراك شهري","اشتراك سنوي"] } ] },
  "subscriptions__youtube-premium": { icon: "fas fa-credit-card", g1: "#EC4899", g2: "#BE185D", order: 189, section: "subscriptions", sectionTitle: "💳 الاشتراكات الرقمية",
    title: "YouTube Premium", intro: "كل خدمات YouTube Premium في مكان واحد — جودة عالية وتنفيذ آمن.",
    groups: [ { h: "خدمات YouTube Premium", items: ["اشتراك شهري","اشتراك سنوي"] } ] },
  "subscriptions__canva-pro": { icon: "fas fa-credit-card", g1: "#EC4899", g2: "#BE185D", order: 190, section: "subscriptions", sectionTitle: "💳 الاشتراكات الرقمية",
    title: "Canva Pro", intro: "كل خدمات Canva Pro في مكان واحد — جودة عالية وتنفيذ آمن.",
    groups: [ { h: "خدمات Canva Pro", items: ["اشتراك شهري","اشتراك سنوي"] } ] },
  "subscriptions__adobe-creative-cloud": { icon: "fas fa-credit-card", g1: "#EC4899", g2: "#BE185D", order: 191, section: "subscriptions", sectionTitle: "💳 الاشتراكات الرقمية",
    title: "Adobe Creative Cloud", intro: "كل خدمات Adobe Creative Cloud في مكان واحد — جودة عالية وتنفيذ آمن.",
    groups: [ { h: "خدمات Adobe Creative Cloud", items: ["اشتراك شهري","اشتراك سنوي"] } ] },
  "subscriptions__microsoft-365": { icon: "fas fa-credit-card", g1: "#EC4899", g2: "#BE185D", order: 192, section: "subscriptions", sectionTitle: "💳 الاشتراكات الرقمية",
    title: "Microsoft 365", intro: "كل خدمات Microsoft 365 في مكان واحد — جودة عالية وتنفيذ آمن.",
    groups: [ { h: "خدمات Microsoft 365", items: ["اشتراك شهري","اشتراك سنوي"] } ] },
  "subscriptions__google-one": { icon: "fas fa-credit-card", g1: "#EC4899", g2: "#BE185D", order: 193, section: "subscriptions", sectionTitle: "💳 الاشتراكات الرقمية",
    title: "Google One", intro: "كل خدمات Google One في مكان واحد — جودة عالية وتنفيذ آمن.",
    groups: [ { h: "خدمات Google One", items: ["اشتراك شهري","اشتراك سنوي"] } ] },
  "subscriptions__chatgpt-plus": { icon: "fas fa-credit-card", g1: "#EC4899", g2: "#BE185D", order: 194, section: "subscriptions", sectionTitle: "💳 الاشتراكات الرقمية",
    title: "ChatGPT Plus", intro: "كل خدمات ChatGPT Plus في مكان واحد — جودة عالية وتنفيذ آمن.",
    groups: [ { h: "خدمات ChatGPT Plus", items: ["اشتراك شهري","اشتراك سنوي"] } ] },
  "subscriptions__claude-pro": { icon: "fas fa-credit-card", g1: "#EC4899", g2: "#BE185D", order: 195, section: "subscriptions", sectionTitle: "💳 الاشتراكات الرقمية",
    title: "Claude Pro", intro: "كل خدمات Claude Pro في مكان واحد — جودة عالية وتنفيذ آمن.",
    groups: [ { h: "خدمات Claude Pro", items: ["اشتراك شهري","اشتراك سنوي"] } ] },
  "subscriptions__capcut-pro": { icon: "fas fa-credit-card", g1: "#EC4899", g2: "#BE185D", order: 196, section: "subscriptions", sectionTitle: "💳 الاشتراكات الرقمية",
    title: "CapCut Pro", intro: "كل خدمات CapCut Pro في مكان واحد — جودة عالية وتنفيذ آمن.",
    groups: [ { h: "خدمات CapCut Pro", items: ["اشتراك شهري","اشتراك سنوي"] } ] },
  "subscriptions__envato-elements": { icon: "fas fa-credit-card", g1: "#EC4899", g2: "#BE185D", order: 197, section: "subscriptions", sectionTitle: "💳 الاشتراكات الرقمية",
    title: "Envato Elements", intro: "كل خدمات Envato Elements في مكان واحد — جودة عالية وتنفيذ آمن.",
    groups: [ { h: "خدمات Envato Elements", items: ["اشتراك شهري","اشتراك سنوي"] } ] },
  "subscriptions__freepik-premium": { icon: "fas fa-credit-card", g1: "#EC4899", g2: "#BE185D", order: 198, section: "subscriptions", sectionTitle: "💳 الاشتراكات الرقمية",
    title: "Freepik Premium", intro: "كل خدمات Freepik Premium في مكان واحد — جودة عالية وتنفيذ آمن.",
    groups: [ { h: "خدمات Freepik Premium", items: ["اشتراك شهري","اشتراك سنوي"] } ] },
  "subscriptions__grammarly-premium": { icon: "fas fa-credit-card", g1: "#EC4899", g2: "#BE185D", order: 199, section: "subscriptions", sectionTitle: "💳 الاشتراكات الرقمية",
    title: "Grammarly Premium", intro: "كل خدمات Grammarly Premium في مكان واحد — جودة عالية وتنفيذ آمن.",
    groups: [ { h: "خدمات Grammarly Premium", items: ["اشتراك شهري","اشتراك سنوي"] } ] },
  "subscriptions__zoom-pro": { icon: "fas fa-credit-card", g1: "#EC4899", g2: "#BE185D", order: 200, section: "subscriptions", sectionTitle: "💳 الاشتراكات الرقمية",
    title: "Zoom Pro", intro: "كل خدمات Zoom Pro في مكان واحد — جودة عالية وتنفيذ آمن.",
    groups: [ { h: "خدمات Zoom Pro", items: ["اشتراك شهري","اشتراك سنوي"] } ] },
  "crypto__binance": { icon: "fab fa-btc", g1: "#F7931A", g2: "#B45309", order: 201, section: "crypto", sectionTitle: "💰 العملات الرقمية",
    title: "Binance", intro: "كل خدمات Binance في مكان واحد — جودة عالية وتنفيذ آمن.",
    groups: [ { h: "خدمات Binance", items: ["حساب موثّق","شحن رصيد","محفظة"] } ] },
  "crypto__bybit": { icon: "fas fa-coins", g1: "#F7931A", g2: "#B45309", order: 202, section: "crypto", sectionTitle: "💰 العملات الرقمية",
    title: "Bybit", intro: "كل خدمات Bybit في مكان واحد — جودة عالية وتنفيذ آمن.",
    groups: [ { h: "خدمات Bybit", items: ["حساب موثّق","شحن رصيد","محفظة"] } ] },
  "crypto__okx": { icon: "fas fa-coins", g1: "#F7931A", g2: "#B45309", order: 203, section: "crypto", sectionTitle: "💰 العملات الرقمية",
    title: "OKX", intro: "كل خدمات OKX في مكان واحد — جودة عالية وتنفيذ آمن.",
    groups: [ { h: "خدمات OKX", items: ["حساب موثّق","شحن رصيد","محفظة"] } ] },
  "crypto__kucoin": { icon: "fas fa-coins", g1: "#F7931A", g2: "#B45309", order: 204, section: "crypto", sectionTitle: "💰 العملات الرقمية",
    title: "KuCoin", intro: "كل خدمات KuCoin في مكان واحد — جودة عالية وتنفيذ آمن.",
    groups: [ { h: "خدمات KuCoin", items: ["حساب موثّق","شحن رصيد","محفظة"] } ] },
  "crypto__coinbase": { icon: "fas fa-coins", g1: "#F7931A", g2: "#B45309", order: 205, section: "crypto", sectionTitle: "💰 العملات الرقمية",
    title: "Coinbase", intro: "كل خدمات Coinbase في مكان واحد — جودة عالية وتنفيذ آمن.",
    groups: [ { h: "خدمات Coinbase", items: ["حساب موثّق","شحن رصيد","محفظة"] } ] },
  "crypto__mexc": { icon: "fas fa-coins", g1: "#F7931A", g2: "#B45309", order: 206, section: "crypto", sectionTitle: "💰 العملات الرقمية",
    title: "MEXC", intro: "كل خدمات MEXC في مكان واحد — جودة عالية وتنفيذ آمن.",
    groups: [ { h: "خدمات MEXC", items: ["حساب موثّق","شحن رصيد","محفظة"] } ] },
  "crypto__bitget": { icon: "fas fa-coins", g1: "#F7931A", g2: "#B45309", order: 207, section: "crypto", sectionTitle: "💰 العملات الرقمية",
    title: "Bitget", intro: "كل خدمات Bitget في مكان واحد — جودة عالية وتنفيذ آمن.",
    groups: [ { h: "خدمات Bitget", items: ["حساب موثّق","شحن رصيد","محفظة"] } ] },
  "crypto__gate-io": { icon: "fas fa-coins", g1: "#F7931A", g2: "#B45309", order: 208, section: "crypto", sectionTitle: "💰 العملات الرقمية",
    title: "Gate.io", intro: "كل خدمات Gate.io في مكان واحد — جودة عالية وتنفيذ آمن.",
    groups: [ { h: "خدمات Gate.io", items: ["حساب موثّق","شحن رصيد","محفظة"] } ] },
  "crypto__coinex": { icon: "fas fa-coins", g1: "#F7931A", g2: "#B45309", order: 209, section: "crypto", sectionTitle: "💰 العملات الرقمية",
    title: "CoinEx", intro: "كل خدمات CoinEx في مكان واحد — جودة عالية وتنفيذ آمن.",
    groups: [ { h: "خدمات CoinEx", items: ["حساب موثّق","شحن رصيد","محفظة"] } ] },
  "crypto__trust-wallet": { icon: "fas fa-coins", g1: "#F7931A", g2: "#B45309", order: 210, section: "crypto", sectionTitle: "💰 العملات الرقمية",
    title: "Trust Wallet", intro: "كل خدمات Trust Wallet في مكان واحد — جودة عالية وتنفيذ آمن.",
    groups: [ { h: "خدمات Trust Wallet", items: ["حساب موثّق","شحن رصيد","محفظة"] } ] },
  "crypto__metamask": { icon: "fas fa-coins", g1: "#F7931A", g2: "#B45309", order: 211, section: "crypto", sectionTitle: "💰 العملات الرقمية",
    title: "MetaMask", intro: "كل خدمات MetaMask في مكان واحد — جودة عالية وتنفيذ آمن.",
    groups: [ { h: "خدمات MetaMask", items: ["حساب موثّق","شحن رصيد","محفظة"] } ] },
  "crypto__phantom-wallet": { icon: "fas fa-coins", g1: "#F7931A", g2: "#B45309", order: 212, section: "crypto", sectionTitle: "💰 العملات الرقمية",
    title: "Phantom Wallet", intro: "كل خدمات Phantom Wallet في مكان واحد — جودة عالية وتنفيذ آمن.",
    groups: [ { h: "خدمات Phantom Wallet", items: ["حساب موثّق","شحن رصيد","محفظة"] } ] },
  "marketing__seo": { icon: "fas fa-arrow-trend-up", g1: "#10B981", g2: "#047857", order: 213, section: "marketing", sectionTitle: "📈 التسويق الرقمي",
    title: "SEO", intro: "كل خدمات SEO في مكان واحد — جودة عالية وتنفيذ آمن.",
    groups: [ { h: "خدمات SEO", items: ["باقة تسويق","استشارة"] } ] },
  "marketing__sem": { icon: "fas fa-arrow-trend-up", g1: "#10B981", g2: "#047857", order: 214, section: "marketing", sectionTitle: "📈 التسويق الرقمي",
    title: "SEM", intro: "كل خدمات SEM في مكان واحد — جودة عالية وتنفيذ آمن.",
    groups: [ { h: "خدمات SEM", items: ["باقة تسويق","استشارة"] } ] },
  "marketing__email-marketing": { icon: "fas fa-arrow-trend-up", g1: "#10B981", g2: "#047857", order: 215, section: "marketing", sectionTitle: "📈 التسويق الرقمي",
    title: "Email Marketing", intro: "كل خدمات Email Marketing في مكان واحد — جودة عالية وتنفيذ آمن.",
    groups: [ { h: "خدمات Email Marketing", items: ["باقة تسويق","استشارة"] } ] },
  "marketing__sms-marketing": { icon: "fas fa-arrow-trend-up", g1: "#10B981", g2: "#047857", order: 216, section: "marketing", sectionTitle: "📈 التسويق الرقمي",
    title: "SMS Marketing", intro: "كل خدمات SMS Marketing في مكان واحد — جودة عالية وتنفيذ آمن.",
    groups: [ { h: "خدمات SMS Marketing", items: ["باقة تسويق","استشارة"] } ] },
  "marketing__google-analytics": { icon: "fas fa-arrow-trend-up", g1: "#10B981", g2: "#047857", order: 217, section: "marketing", sectionTitle: "📈 التسويق الرقمي",
    title: "Google Analytics", intro: "كل خدمات Google Analytics في مكان واحد — جودة عالية وتنفيذ آمن.",
    groups: [ { h: "خدمات Google Analytics", items: ["باقة تسويق","استشارة"] } ] },
  "marketing__social-media-management": { icon: "fas fa-arrow-trend-up", g1: "#10B981", g2: "#047857", order: 218, section: "marketing", sectionTitle: "📈 التسويق الرقمي",
    title: "Social Media Management", intro: "كل خدمات Social Media Management في مكان واحد — جودة عالية وتنفيذ آمن.",
    groups: [ { h: "خدمات Social Media Management", items: ["باقة تسويق","استشارة"] } ] },
  "marketing__branding": { icon: "fas fa-arrow-trend-up", g1: "#10B981", g2: "#047857", order: 219, section: "marketing", sectionTitle: "📈 التسويق الرقمي",
    title: "Branding", intro: "كل خدمات Branding في مكان واحد — جودة عالية وتنفيذ آمن.",
    groups: [ { h: "خدمات Branding", items: ["باقة تسويق","استشارة"] } ] },
  "marketing__x": { icon: "fas fa-arrow-trend-up", g1: "#10B981", g2: "#047857", order: 220, section: "marketing", sectionTitle: "📈 التسويق الرقمي",
    title: "صناعة المحتوى", intro: "كل خدمات صناعة المحتوى في مكان واحد — جودة عالية وتنفيذ آمن.",
    groups: [ { h: "خدمات صناعة المحتوى", items: ["باقة تسويق","استشارة"] } ] },
  "escrow__x": { icon: "fas fa-handshake", g1: "#14B8A6", g2: "#0F766E", order: 221, section: "escrow", sectionTitle: "🤝 الوساطة الآمنة",
    title: "وساطة الحسابات", intro: "كل خدمات وساطة الحسابات في مكان واحد — جودة عالية وتنفيذ آمن.",
    groups: [ { h: "خدمات وساطة الحسابات", items: ["وساطة آمنة"] } ] },
  "escrow__x-2": { icon: "fas fa-handshake", g1: "#14B8A6", g2: "#0F766E", order: 222, section: "escrow", sectionTitle: "🤝 الوساطة الآمنة",
    title: "وساطة الصفحات", intro: "كل خدمات وساطة الصفحات في مكان واحد — جودة عالية وتنفيذ آمن.",
    groups: [ { h: "خدمات وساطة الصفحات", items: ["وساطة آمنة"] } ] },
  "escrow__x-3": { icon: "fas fa-handshake", g1: "#14B8A6", g2: "#0F766E", order: 223, section: "escrow", sectionTitle: "🤝 الوساطة الآمنة",
    title: "وساطة القنوات", intro: "كل خدمات وساطة القنوات في مكان واحد — جودة عالية وتنفيذ آمن.",
    groups: [ { h: "خدمات وساطة القنوات", items: ["وساطة آمنة"] } ] },
  "escrow__x-4": { icon: "fas fa-handshake", g1: "#14B8A6", g2: "#0F766E", order: 224, section: "escrow", sectionTitle: "🤝 الوساطة الآمنة",
    title: "وساطة المواقع", intro: "كل خدمات وساطة المواقع في مكان واحد — جودة عالية وتنفيذ آمن.",
    groups: [ { h: "خدمات وساطة المواقع", items: ["وساطة آمنة"] } ] },
  "escrow__x-5": { icon: "fas fa-handshake", g1: "#14B8A6", g2: "#0F766E", order: 225, section: "escrow", sectionTitle: "🤝 الوساطة الآمنة",
    title: "وساطة الدومينات", intro: "كل خدمات وساطة الدومينات في مكان واحد — جودة عالية وتنفيذ آمن.",
    groups: [ { h: "خدمات وساطة الدومينات", items: ["وساطة آمنة"] } ] },
  "escrow__x-6": { icon: "fas fa-handshake", g1: "#14B8A6", g2: "#0F766E", order: 226, section: "escrow", sectionTitle: "🤝 الوساطة الآمنة",
    title: "وساطة العملات", intro: "كل خدمات وساطة العملات في مكان واحد — جودة عالية وتنفيذ آمن.",
    groups: [ { h: "خدمات وساطة العملات", items: ["وساطة آمنة"] } ] },
  "escrow__x-7": { icon: "fas fa-handshake", g1: "#14B8A6", g2: "#0F766E", order: 227, section: "escrow", sectionTitle: "🤝 الوساطة الآمنة",
    title: "وساطة التطبيقات", intro: "كل خدمات وساطة التطبيقات في مكان واحد — جودة عالية وتنفيذ آمن.",
    groups: [ { h: "خدمات وساطة التطبيقات", items: ["وساطة آمنة"] } ] },
  "escrow__x-8": { icon: "fas fa-handshake", g1: "#14B8A6", g2: "#0F766E", order: 228, section: "escrow", sectionTitle: "🤝 الوساطة الآمنة",
    title: "وساطة الاشتراكات", intro: "كل خدمات وساطة الاشتراكات في مكان واحد — جودة عالية وتنفيذ آمن.",
    groups: [ { h: "خدمات وساطة الاشتراكات", items: ["وساطة آمنة"] } ] },
  "vnumbers__x": { icon: "fas fa-mobile-screen-button", g1: "#3B82F6", g2: "#1D4ED8", order: 229, section: "vnumbers", sectionTitle: "📲 أرقام افتراضية",
    title: "أرقام تفعيل واتساب", intro: "كل خدمات أرقام تفعيل واتساب في مكان واحد — جودة عالية وتنفيذ آمن.",
    groups: [ { h: "خدمات أرقام تفعيل واتساب", items: ["رقم تفعيل"] } ] },
  "vnumbers__x-2": { icon: "fas fa-mobile-screen-button", g1: "#3B82F6", g2: "#1D4ED8", order: 230, section: "vnumbers", sectionTitle: "📲 أرقام افتراضية",
    title: "أرقام تفعيل تيليجرام", intro: "كل خدمات أرقام تفعيل تيليجرام في مكان واحد — جودة عالية وتنفيذ آمن.",
    groups: [ { h: "خدمات أرقام تفعيل تيليجرام", items: ["رقم تفعيل"] } ] },
  "vnumbers__x-3": { icon: "fas fa-mobile-screen-button", g1: "#3B82F6", g2: "#1D4ED8", order: 231, section: "vnumbers", sectionTitle: "📲 أرقام افتراضية",
    title: "أرقام تفعيل جوجل", intro: "كل خدمات أرقام تفعيل جوجل في مكان واحد — جودة عالية وتنفيذ آمن.",
    groups: [ { h: "خدمات أرقام تفعيل جوجل", items: ["رقم تفعيل"] } ] },
  "vnumbers__x-4": { icon: "fas fa-mobile-screen-button", g1: "#3B82F6", g2: "#1D4ED8", order: 232, section: "vnumbers", sectionTitle: "📲 أرقام افتراضية",
    title: "أرقام تفعيل فيسبوك", intro: "كل خدمات أرقام تفعيل فيسبوك في مكان واحد — جودة عالية وتنفيذ آمن.",
    groups: [ { h: "خدمات أرقام تفعيل فيسبوك", items: ["رقم تفعيل"] } ] },
  "vnumbers__x-5": { icon: "fas fa-mobile-screen-button", g1: "#3B82F6", g2: "#1D4ED8", order: 233, section: "vnumbers", sectionTitle: "📲 أرقام افتراضية",
    title: "أرقام تفعيل إنستجرام", intro: "كل خدمات أرقام تفعيل إنستجرام في مكان واحد — جودة عالية وتنفيذ آمن.",
    groups: [ { h: "خدمات أرقام تفعيل إنستجرام", items: ["رقم تفعيل"] } ] },
  "esim__esim": { icon: "fas fa-sim-card", g1: "#06B6D4", g2: "#0E7490", order: 234, section: "esim", sectionTitle: "📞 شرائح eSIM",
    title: "eSIM سفر", intro: "كل خدمات eSIM سفر في مكان واحد — جودة عالية وتنفيذ آمن.",
    groups: [ { h: "خدمات eSIM سفر", items: ["باقة eSIM"] } ] },
  "esim__esim-2": { icon: "fas fa-sim-card", g1: "#06B6D4", g2: "#0E7490", order: 235, section: "esim", sectionTitle: "📞 شرائح eSIM",
    title: "eSIM دولية", intro: "كل خدمات eSIM دولية في مكان واحد — جودة عالية وتنفيذ آمن.",
    groups: [ { h: "خدمات eSIM دولية", items: ["باقة eSIM"] } ] },
  "esim__esim-3": { icon: "fas fa-sim-card", g1: "#06B6D4", g2: "#0E7490", order: 236, section: "esim", sectionTitle: "📞 شرائح eSIM",
    title: "eSIM بيانات", intro: "كل خدمات eSIM بيانات في مكان واحد — جودة عالية وتنفيذ آمن.",
    groups: [ { h: "خدمات eSIM بيانات", items: ["باقة eSIM"] } ] },
  "esim__esim-4": { icon: "fas fa-sim-card", g1: "#06B6D4", g2: "#0E7490", order: 237, section: "esim", sectionTitle: "📞 شرائح eSIM",
    title: "باقات eSIM شهرية", intro: "كل خدمات باقات eSIM شهرية في مكان واحد — جودة عالية وتنفيذ آمن.",
    groups: [ { h: "خدمات باقات eSIM شهرية", items: ["باقة eSIM"] } ] },
  "vpn__vpn": { icon: "fas fa-user-shield", g1: "#22D3EE", g2: "#0891B2", order: 238, section: "vpn", sectionTitle: "🌍 VPN & Proxy",
    title: "اشتراك VPN", intro: "كل خدمات اشتراك VPN في مكان واحد — جودة عالية وتنفيذ آمن.",
    groups: [ { h: "خدمات اشتراك VPN", items: ["اشتراك"] } ] },
  "vpn__proxy": { icon: "fas fa-user-shield", g1: "#22D3EE", g2: "#0891B2", order: 239, section: "vpn", sectionTitle: "🌍 VPN & Proxy",
    title: "Proxy سكني", intro: "كل خدمات Proxy سكني في مكان واحد — جودة عالية وتنفيذ آمن.",
    groups: [ { h: "خدمات Proxy سكني", items: ["اشتراك"] } ] },
  "vpn__proxy-2": { icon: "fas fa-user-shield", g1: "#22D3EE", g2: "#0891B2", order: 240, section: "vpn", sectionTitle: "🌍 VPN & Proxy",
    title: "Proxy داتا سنتر", intro: "كل خدمات Proxy داتا سنتر في مكان واحد — جودة عالية وتنفيذ آمن.",
    groups: [ { h: "خدمات Proxy داتا سنتر", items: ["اشتراك"] } ] },
  "vpn__proxy-3": { icon: "fas fa-user-shield", g1: "#22D3EE", g2: "#0891B2", order: 241, section: "vpn", sectionTitle: "🌍 VPN & Proxy",
    title: "Proxy موبايل", intro: "كل خدمات Proxy موبايل في مكان واحد — جودة عالية وتنفيذ آمن.",
    groups: [ { h: "خدمات Proxy موبايل", items: ["اشتراك"] } ] },
  "vpn__ip": { icon: "fas fa-user-shield", g1: "#22D3EE", g2: "#0891B2", order: 242, section: "vpn", sectionTitle: "🌍 VPN & Proxy",
    title: "IP ثابت", intro: "كل خدمات IP ثابت في مكان واحد — جودة عالية وتنفيذ آمن.",
    groups: [ { h: "خدمات IP ثابت", items: ["اشتراك"] } ] },
  "cdn__cloudflare": { icon: "fas fa-server", g1: "#64748B", g2: "#334155", order: 243, section: "cdn", sectionTitle: "🌐 CDN & DNS",
    title: "Cloudflare", intro: "كل خدمات Cloudflare في مكان واحد — جودة عالية وتنفيذ آمن.",
    groups: [ { h: "خدمات Cloudflare", items: ["إعداد","اشتراك"] } ] },
  "cdn__cdn": { icon: "fas fa-server", g1: "#64748B", g2: "#334155", order: 244, section: "cdn", sectionTitle: "🌐 CDN & DNS",
    title: "تسريع CDN", intro: "كل خدمات تسريع CDN في مكان واحد — جودة عالية وتنفيذ آمن.",
    groups: [ { h: "خدمات تسريع CDN", items: ["إعداد","اشتراك"] } ] },
  "cdn__dns": { icon: "fas fa-server", g1: "#64748B", g2: "#334155", order: 245, section: "cdn", sectionTitle: "🌐 CDN & DNS",
    title: "إدارة DNS", intro: "كل خدمات إدارة DNS في مكان واحد — جودة عالية وتنفيذ آمن.",
    groups: [ { h: "خدمات إدارة DNS", items: ["إعداد","اشتراك"] } ] },
  "cdn__ddos": { icon: "fas fa-server", g1: "#64748B", g2: "#334155", order: 246, section: "cdn", sectionTitle: "🌐 CDN & DNS",
    title: "حماية DDoS", intro: "كل خدمات حماية DDoS في مكان واحد — جودة عالية وتنفيذ آمن.",
    groups: [ { h: "خدمات حماية DDoS", items: ["إعداد","اشتراك"] } ] },
  "cdn__ssl": { icon: "fas fa-server", g1: "#64748B", g2: "#334155", order: 247, section: "cdn", sectionTitle: "🌐 CDN & DNS",
    title: "شهادات SSL", intro: "كل خدمات شهادات SSL في مكان واحد — جودة عالية وتنفيذ آمن.",
    groups: [ { h: "خدمات شهادات SSL", items: ["إعداد","اشتراك"] } ] },
  "design__x": { icon: "fas fa-palette", g1: "#F472B6", g2: "#DB2777", order: 248, section: "design", sectionTitle: "🎨 التصميم والجرافيك",
    title: "تصميم لوجو", intro: "كل خدمات تصميم لوجو في مكان واحد — جودة عالية وتنفيذ آمن.",
    groups: [ { h: "خدمات تصميم لوجو", items: ["تصميم"] } ] },
  "design__x-2": { icon: "fas fa-palette", g1: "#F472B6", g2: "#DB2777", order: 249, section: "design", sectionTitle: "🎨 التصميم والجرافيك",
    title: "هوية بصرية", intro: "كل خدمات هوية بصرية في مكان واحد — جودة عالية وتنفيذ آمن.",
    groups: [ { h: "خدمات هوية بصرية", items: ["تصميم"] } ] },
  "design__x-3": { icon: "fas fa-palette", g1: "#F472B6", g2: "#DB2777", order: 250, section: "design", sectionTitle: "🎨 التصميم والجرافيك",
    title: "بوستات سوشيال ميديا", intro: "كل خدمات بوستات سوشيال ميديا في مكان واحد — جودة عالية وتنفيذ آمن.",
    groups: [ { h: "خدمات بوستات سوشيال ميديا", items: ["تصميم"] } ] },
  "design__x-4": { icon: "fas fa-palette", g1: "#F472B6", g2: "#DB2777", order: 251, section: "design", sectionTitle: "🎨 التصميم والجرافيك",
    title: "موشن جرافيك", intro: "كل خدمات موشن جرافيك في مكان واحد — جودة عالية وتنفيذ آمن.",
    groups: [ { h: "خدمات موشن جرافيك", items: ["تصميم"] } ] },
  "design__3d": { icon: "fas fa-palette", g1: "#F472B6", g2: "#DB2777", order: 252, section: "design", sectionTitle: "🎨 التصميم والجرافيك",
    title: "تصميم 3D", intro: "كل خدمات تصميم 3D في مكان واحد — جودة عالية وتنفيذ آمن.",
    groups: [ { h: "خدمات تصميم 3D", items: ["تصميم"] } ] },
  "design__ui-ux": { icon: "fas fa-palette", g1: "#F472B6", g2: "#DB2777", order: 253, section: "design", sectionTitle: "🎨 التصميم والجرافيك",
    title: "UI/UX", intro: "كل خدمات UI/UX في مكان واحد — جودة عالية وتنفيذ آمن.",
    groups: [ { h: "خدمات UI/UX", items: ["تصميم"] } ] },
  "design__x-5": { icon: "fas fa-palette", g1: "#F472B6", g2: "#DB2777", order: 254, section: "design", sectionTitle: "🎨 التصميم والجرافيك",
    title: "بنرات إعلانية", intro: "كل خدمات بنرات إعلانية في مكان واحد — جودة عالية وتنفيذ آمن.",
    groups: [ { h: "خدمات بنرات إعلانية", items: ["تصميم"] } ] },
  "print__x": { icon: "fas fa-print", g1: "#FB7185", g2: "#E11D48", order: 255, section: "print", sectionTitle: "🖨️ الطباعة عند الطلب",
    title: "طباعة تيشيرتات", intro: "كل خدمات طباعة تيشيرتات في مكان واحد — جودة عالية وتنفيذ آمن.",
    groups: [ { h: "خدمات طباعة تيشيرتات", items: ["طلب طباعة"] } ] },
  "print__x-2": { icon: "fas fa-print", g1: "#FB7185", g2: "#E11D48", order: 256, section: "print", sectionTitle: "🖨️ الطباعة عند الطلب",
    title: "مج وأكواب", intro: "كل خدمات مج وأكواب في مكان واحد — جودة عالية وتنفيذ آمن.",
    groups: [ { h: "خدمات مج وأكواب", items: ["طلب طباعة"] } ] },
  "print__x-3": { icon: "fas fa-print", g1: "#FB7185", g2: "#E11D48", order: 257, section: "print", sectionTitle: "🖨️ الطباعة عند الطلب",
    title: "استيكرات", intro: "كل خدمات استيكرات في مكان واحد — جودة عالية وتنفيذ آمن.",
    groups: [ { h: "خدمات استيكرات", items: ["طلب طباعة"] } ] },
  "print__x-4": { icon: "fas fa-print", g1: "#FB7185", g2: "#E11D48", order: 258, section: "print", sectionTitle: "🖨️ الطباعة عند الطلب",
    title: "بوسترات", intro: "كل خدمات بوسترات في مكان واحد — جودة عالية وتنفيذ آمن.",
    groups: [ { h: "خدمات بوسترات", items: ["طلب طباعة"] } ] },
  "print__x-5": { icon: "fas fa-print", g1: "#FB7185", g2: "#E11D48", order: 259, section: "print", sectionTitle: "🖨️ الطباعة عند الطلب",
    title: "كروت شخصية", intro: "كل خدمات كروت شخصية في مكان واحد — جودة عالية وتنفيذ آمن.",
    groups: [ { h: "خدمات كروت شخصية", items: ["طلب طباعة"] } ] },
  "courses__x": { icon: "fas fa-graduation-cap", g1: "#A78BFA", g2: "#7C3AED", order: 260, section: "courses", sectionTitle: "📚 الدورات التعليمية",
    title: "دورات برمجة", intro: "كل خدمات دورات برمجة في مكان واحد — جودة عالية وتنفيذ آمن.",
    groups: [ { h: "خدمات دورات برمجة", items: ["اشتراك دورة"] } ] },
  "courses__x-2": { icon: "fas fa-graduation-cap", g1: "#A78BFA", g2: "#7C3AED", order: 261, section: "courses", sectionTitle: "📚 الدورات التعليمية",
    title: "دورات تسويق", intro: "كل خدمات دورات تسويق في مكان واحد — جودة عالية وتنفيذ آمن.",
    groups: [ { h: "خدمات دورات تسويق", items: ["اشتراك دورة"] } ] },
  "courses__x-3": { icon: "fas fa-graduation-cap", g1: "#A78BFA", g2: "#7C3AED", order: 262, section: "courses", sectionTitle: "📚 الدورات التعليمية",
    title: "دورات تصميم", intro: "كل خدمات دورات تصميم في مكان واحد — جودة عالية وتنفيذ آمن.",
    groups: [ { h: "خدمات دورات تصميم", items: ["اشتراك دورة"] } ] },
  "courses__x-4": { icon: "fas fa-graduation-cap", g1: "#A78BFA", g2: "#7C3AED", order: 263, section: "courses", sectionTitle: "📚 الدورات التعليمية",
    title: "دورات ذكاء اصطناعي", intro: "كل خدمات دورات ذكاء اصطناعي في مكان واحد — جودة عالية وتنفيذ آمن.",
    groups: [ { h: "خدمات دورات ذكاء اصطناعي", items: ["اشتراك دورة"] } ] },
  "courses__x-5": { icon: "fas fa-graduation-cap", g1: "#A78BFA", g2: "#7C3AED", order: 264, section: "courses", sectionTitle: "📚 الدورات التعليمية",
    title: "دورات تداول", intro: "كل خدمات دورات تداول في مكان واحد — جودة عالية وتنفيذ آمن.",
    groups: [ { h: "خدمات دورات تداول", items: ["اشتراك دورة"] } ] },
  "courses__x-6": { icon: "fas fa-graduation-cap", g1: "#A78BFA", g2: "#7C3AED", order: 265, section: "courses", sectionTitle: "📚 الدورات التعليمية",
    title: "دورات لغات", intro: "كل خدمات دورات لغات في مكان واحد — جودة عالية وتنفيذ آمن.",
    groups: [ { h: "خدمات دورات لغات", items: ["اشتراك دورة"] } ] },
  "business__x": { icon: "fas fa-briefcase", g1: "#94A3B8", g2: "#475569", order: 266, section: "business", sectionTitle: "💼 الأعمال والشركات",
    title: "تأسيس شركات", intro: "كل خدمات تأسيس شركات في مكان واحد — جودة عالية وتنفيذ آمن.",
    groups: [ { h: "خدمات تأسيس شركات", items: ["استشارة","باقة"] } ] },
  "business__x-2": { icon: "fas fa-briefcase", g1: "#94A3B8", g2: "#475569", order: 267, section: "business", sectionTitle: "💼 الأعمال والشركات",
    title: "خطط أعمال", intro: "كل خدمات خطط أعمال في مكان واحد — جودة عالية وتنفيذ آمن.",
    groups: [ { h: "خدمات خطط أعمال", items: ["استشارة","باقة"] } ] },
  "business__x-3": { icon: "fas fa-briefcase", g1: "#94A3B8", g2: "#475569", order: 268, section: "business", sectionTitle: "💼 الأعمال والشركات",
    title: "استشارات تسويقية", intro: "كل خدمات استشارات تسويقية في مكان واحد — جودة عالية وتنفيذ آمن.",
    groups: [ { h: "خدمات استشارات تسويقية", items: ["استشارة","باقة"] } ] },
  "business__x-4": { icon: "fas fa-briefcase", g1: "#94A3B8", g2: "#475569", order: 269, section: "business", sectionTitle: "💼 الأعمال والشركات",
    title: "إدارة مشاريع", intro: "كل خدمات إدارة مشاريع في مكان واحد — جودة عالية وتنفيذ آمن.",
    groups: [ { h: "خدمات إدارة مشاريع", items: ["استشارة","باقة"] } ] },
  "business__crm": { icon: "fas fa-briefcase", g1: "#94A3B8", g2: "#475569", order: 270, section: "business", sectionTitle: "💼 الأعمال والشركات",
    title: "أنظمة CRM", intro: "كل خدمات أنظمة CRM في مكان واحد — جودة عالية وتنفيذ آمن.",
    groups: [ { h: "خدمات أنظمة CRM", items: ["استشارة","باقة"] } ] },
  "licenses__windows": { icon: "fas fa-key", g1: "#FACC15", g2: "#CA8A04", order: 271, section: "licenses", sectionTitle: "🔑 التراخيص والمفاتيح",
    title: "مفاتيح Windows", intro: "كل خدمات مفاتيح Windows في مكان واحد — جودة عالية وتنفيذ آمن.",
    groups: [ { h: "خدمات مفاتيح Windows", items: ["مفتاح ترخيص"] } ] },
  "licenses__office": { icon: "fas fa-key", g1: "#FACC15", g2: "#CA8A04", order: 272, section: "licenses", sectionTitle: "🔑 التراخيص والمفاتيح",
    title: "مفاتيح Office", intro: "كل خدمات مفاتيح Office في مكان واحد — جودة عالية وتنفيذ آمن.",
    groups: [ { h: "خدمات مفاتيح Office", items: ["مفتاح ترخيص"] } ] },
  "licenses__x": { icon: "fas fa-key", g1: "#FACC15", g2: "#CA8A04", order: 273, section: "licenses", sectionTitle: "🔑 التراخيص والمفاتيح",
    title: "برامج أنتي فايروس", intro: "كل خدمات برامج أنتي فايروس في مكان واحد — جودة عالية وتنفيذ آمن.",
    groups: [ { h: "خدمات برامج أنتي فايروس", items: ["مفتاح ترخيص"] } ] },
  "licenses__x-2": { icon: "fas fa-key", g1: "#FACC15", g2: "#CA8A04", order: 274, section: "licenses", sectionTitle: "🔑 التراخيص والمفاتيح",
    title: "تراخيص برامج", intro: "كل خدمات تراخيص برامج في مكان واحد — جودة عالية وتنفيذ آمن.",
    groups: [ { h: "خدمات تراخيص برامج", items: ["مفتاح ترخيص"] } ] },
  "licenses__x-3": { icon: "fas fa-key", g1: "#FACC15", g2: "#CA8A04", order: 275, section: "licenses", sectionTitle: "🔑 التراخيص والمفاتيح",
    title: "مفاتيح ألعاب", intro: "كل خدمات مفاتيح ألعاب في مكان واحد — جودة عالية وتنفيذ آمن.",
    groups: [ { h: "خدمات مفاتيح ألعاب", items: ["مفتاح ترخيص"] } ] },
  "giftcards__itunes": { icon: "fas fa-gift", g1: "#F43F5E", g2: "#E11D48", order: 276, section: "giftcards", sectionTitle: "🎁 بطاقات الهدايا",
    title: "iTunes", intro: "كل خدمات iTunes في مكان واحد — جودة عالية وتنفيذ آمن.",
    groups: [ { h: "خدمات iTunes", items: ["بطاقة هدية"] } ] },
  "giftcards__google-play": { icon: "fas fa-gift", g1: "#F43F5E", g2: "#E11D48", order: 277, section: "giftcards", sectionTitle: "🎁 بطاقات الهدايا",
    title: "Google Play", intro: "كل خدمات Google Play في مكان واحد — جودة عالية وتنفيذ آمن.",
    groups: [ { h: "خدمات Google Play", items: ["بطاقة هدية"] } ] },
  "giftcards__steam": { icon: "fab fa-steam", g1: "#F43F5E", g2: "#E11D48", order: 278, section: "giftcards", sectionTitle: "🎁 بطاقات الهدايا",
    title: "Steam", intro: "كل خدمات Steam في مكان واحد — جودة عالية وتنفيذ آمن.",
    groups: [ { h: "خدمات Steam", items: ["بطاقة هدية"] } ] },
  "giftcards__playstation": { icon: "fab fa-playstation", g1: "#F43F5E", g2: "#E11D48", order: 279, section: "giftcards", sectionTitle: "🎁 بطاقات الهدايا",
    title: "PlayStation", intro: "كل خدمات PlayStation في مكان واحد — جودة عالية وتنفيذ آمن.",
    groups: [ { h: "خدمات PlayStation", items: ["بطاقة هدية"] } ] },
  "giftcards__xbox": { icon: "fab fa-xbox", g1: "#F43F5E", g2: "#E11D48", order: 280, section: "giftcards", sectionTitle: "🎁 بطاقات الهدايا",
    title: "Xbox", intro: "كل خدمات Xbox في مكان واحد — جودة عالية وتنفيذ آمن.",
    groups: [ { h: "خدمات Xbox", items: ["بطاقة هدية"] } ] },
  "giftcards__amazon": { icon: "fab fa-amazon", g1: "#F43F5E", g2: "#E11D48", order: 281, section: "giftcards", sectionTitle: "🎁 بطاقات الهدايا",
    title: "Amazon", intro: "كل خدمات Amazon في مكان واحد — جودة عالية وتنفيذ آمن.",
    groups: [ { h: "خدمات Amazon", items: ["بطاقة هدية"] } ] },
  "giftcards__netflix": { icon: "fas fa-gift", g1: "#F43F5E", g2: "#E11D48", order: 282, section: "giftcards", sectionTitle: "🎁 بطاقات الهدايا",
    title: "Netflix", intro: "كل خدمات Netflix في مكان واحد — جودة عالية وتنفيذ آمن.",
    groups: [ { h: "خدمات Netflix", items: ["بطاقة هدية"] } ] },
  "giftcards__roblox": { icon: "fas fa-gift", g1: "#F43F5E", g2: "#E11D48", order: 283, section: "giftcards", sectionTitle: "🎁 بطاقات الهدايا",
    title: "Roblox", intro: "كل خدمات Roblox في مكان واحد — جودة عالية وتنفيذ آمن.",
    groups: [ { h: "خدمات Roblox", items: ["بطاقة هدية"] } ] }
};
// Default section dividers (banners) — one per section, before its first platform card.
window.DEFAULT_DIVIDERS = [
  { title: "🤖 اشتراكات وحسابات الذكاء الاصطناعي", sub: "", before: "ai__chatgpt", g1: "#7C3AED", g2: "#4F46E5", titleSize: "md", radius: 14, arts: [], active: true },
  { title: "📱 منصات التواصل الاجتماعي", sub: "", before: "social__facebook", g1: "#2F6FED", g2: "#17C8AC", titleSize: "md", radius: 14, arts: [], active: true },
  { title: "🎮 شحن الألعاب", sub: "", before: "games__pubg-mobile", g1: "#F43F5E", g2: "#FB923C", titleSize: "md", radius: 14, arts: [], active: true },
  { title: "💻 البرمجة والتطوير", sub: "", before: "dev__x", g1: "#0EA5E9", g2: "#2563EB", titleSize: "md", radius: 14, arts: [], active: true },
  { title: "🎬 المونتاج وتصميم الفيديو", sub: "", before: "montage__x", g1: "#E0208F", g2: "#7C3AED", titleSize: "md", radius: 14, arts: [], active: true },
  { title: "🎵 منصات الموسيقى", sub: "", before: "music__spotify", g1: "#1DB954", g2: "#059669", titleSize: "md", radius: 14, arts: [], active: true },
  { title: "🎞️ منصات الفيديو والبث", sub: "", before: "video__youtube", g1: "#EF4444", g2: "#B91C1C", titleSize: "md", radius: 14, arts: [], active: true },
  { title: "📧 البريد الإلكتروني", sub: "", before: "email__gmail", g1: "#F59E0B", g2: "#D97706", titleSize: "md", radius: 14, arts: [], active: true },
  { title: "☁️ التخزين السحابي", sub: "", before: "cloud__google-drive", g1: "#38BDF8", g2: "#0284C7", titleSize: "md", radius: 14, arts: [], active: true },
  { title: "🌐 المواقع والمتاجر", sub: "", before: "web__x", g1: "#14B8A6", g2: "#0D9488", titleSize: "md", radius: 14, arts: [], active: true },
  { title: "📢 الإعلانات الممولة", sub: "", before: "ads__meta-ads", g1: "#6366F1", g2: "#4338CA", titleSize: "md", radius: 14, arts: [], active: true },
  { title: "🛒 البيع والشراء", sub: "", before: "trade__x", g1: "#F97316", g2: "#EA580C", titleSize: "md", radius: 14, arts: [], active: true },
  { title: "✅ التوثيق الرسمي", sub: "", before: "verify__facebook", g1: "#22C55E", g2: "#15803D", titleSize: "md", radius: 14, arts: [], active: true },
  { title: "🛡️ الحماية والاسترجاع", sub: "", before: "protect__x", g1: "#0EA5E9", g2: "#155E75", titleSize: "md", radius: 14, arts: [], active: true },
  { title: "📊 خدمات SMM", sub: "", before: "smm__x", g1: "#8B5CF6", g2: "#6D28D9", titleSize: "md", radius: 14, arts: [], active: true },
  { title: "💳 الاشتراكات الرقمية", sub: "", before: "subscriptions__netflix", g1: "#EC4899", g2: "#BE185D", titleSize: "md", radius: 14, arts: [], active: true },
  { title: "💰 العملات الرقمية", sub: "", before: "crypto__binance", g1: "#F7931A", g2: "#B45309", titleSize: "md", radius: 14, arts: [], active: true },
  { title: "📈 التسويق الرقمي", sub: "", before: "marketing__seo", g1: "#10B981", g2: "#047857", titleSize: "md", radius: 14, arts: [], active: true },
  { title: "🤝 الوساطة الآمنة", sub: "", before: "escrow__x", g1: "#14B8A6", g2: "#0F766E", titleSize: "md", radius: 14, arts: [], active: true },
  { title: "📲 أرقام افتراضية", sub: "", before: "vnumbers__x", g1: "#3B82F6", g2: "#1D4ED8", titleSize: "md", radius: 14, arts: [], active: true },
  { title: "📞 شرائح eSIM", sub: "", before: "esim__esim", g1: "#06B6D4", g2: "#0E7490", titleSize: "md", radius: 14, arts: [], active: true },
  { title: "🌍 VPN & Proxy", sub: "", before: "vpn__vpn", g1: "#22D3EE", g2: "#0891B2", titleSize: "md", radius: 14, arts: [], active: true },
  { title: "🌐 CDN & DNS", sub: "", before: "cdn__cloudflare", g1: "#64748B", g2: "#334155", titleSize: "md", radius: 14, arts: [], active: true },
  { title: "🎨 التصميم والجرافيك", sub: "", before: "design__x", g1: "#F472B6", g2: "#DB2777", titleSize: "md", radius: 14, arts: [], active: true },
  { title: "🖨️ الطباعة عند الطلب", sub: "", before: "print__x", g1: "#FB7185", g2: "#E11D48", titleSize: "md", radius: 14, arts: [], active: true },
  { title: "📚 الدورات التعليمية", sub: "", before: "courses__x", g1: "#A78BFA", g2: "#7C3AED", titleSize: "md", radius: 14, arts: [], active: true },
  { title: "💼 الأعمال والشركات", sub: "", before: "business__x", g1: "#94A3B8", g2: "#475569", titleSize: "md", radius: 14, arts: [], active: true },
  { title: "🔑 التراخيص والمفاتيح", sub: "", before: "licenses__windows", g1: "#FACC15", g2: "#CA8A04", titleSize: "md", radius: 14, arts: [], active: true },
  { title: "🎁 بطاقات الهدايا", sub: "", before: "giftcards__itunes", g1: "#F43F5E", g2: "#E11D48", titleSize: "md", radius: 14, arts: [], active: true }
];
